ledger-core/v2/vanilla/reflectkit/func_code_test.go

moved speedtest to benchmark, so it won't run on testing and could be interpreted as benchmark

NOISSUE: move speedtest to benchmark

---

ledger-core/v2/conveyor/pulse_cache.go
ledger-core/v2/conveyor/sm_pulse_slot.go
ledger-core/v2/conveyor/smachine/api_adapter.go
ledger-core/v2/conveyor/smachine/api_context.go
ledger-core/v2/conveyor/smachine/slot_machine.go
ledger-core/v2/conveyor/smachine/sync_queue.go
ledger-core/v2/log/adapters/bilog/adapter_test.go
ledger-core/v2/log/adapters/bilog/builder.go
ledger-core/v2/log/outputsyslog/logger_syslog.go
ledger-core/v2/vanilla/keyset/keyset_overlay.go
ledger-core/v2/vanilla/keyset/keyset_test.go
ledger-core/v2/vanilla/longbits/byte_string.go

assigned TODO to jira tickets
All that left are TODO in examples

NOISSUE: TODO tickets assignment

---

ledger-core/v2/ledger-v2/smachines/adapters.go
ledger-core/v2/ledger-v2/smachines/drop.go
ledger-core/v2/ledger-v2/smachines/object.go
ledger-core/v2/ledger-v2/smachines/set_result.go
ledger-core/v2/ledger-v2/store/record.go
ledger-core/v2/server/internal/light/v2/components.go

Add adapters.

---

ledger-core/v2/vanilla/longbits/bytestring.go
ledger-core/v2/vanilla/longbits/bytestring_test.go

- fixed broken TestByteString_IsEmpty
- removed outdated comment

NOISSUE: fixed broken TestByteString_IsEmpty

---

ledger-core/v2/vanilla/keyset/keyset_test.go

added test case for independence of copy and inversed copy

PLAT-16: test independence of Copy and InversedCopy

---

ledger-core/v2/conveyor/pulse_manager.go
ledger-core/v2/conveyor/pulse_manager_test.go
ledger-core/v2/conveyor/smachine/exec_adapter.go

added unit tests for PulseDataManager public methods

PLAT-83: added unit tests for PulseDataManager public methods

---

ledger-core/v2/conveyor/conveyor.go
ledger-core/v2/conveyor/conveyor_test.go

added unit tests for basic conveyor operations
some parts with Antique pulse state is not quite clear, so for now I am not sure how to test them

PLAT-18: add units for basic conveyor operations

---

ledger-core/v2/log/builder.go
ledger-core/v2/log/logger.go

- some extra documentation for logger
- fixed documentation to respect godoc formatting

PLAT-81: extra doc for logger methods

---

ledger-core/v2/instrumentation/introspector/swagger_const_gen.go
ledger-core/v2/network/consensus/common/endpoints/inbound_mock.go
ledger-core/v2/network/consensus/gcpv2/api/candidate_control_feeder_mock.go
ledger-core/v2/network/consensus/gcpv2/api/census/active_mock.go
ledger-core/v2/network/consensus/gcpv2/api/census/expected_mock.go
ledger-core/v2/network/consensus/gcpv2/api/census/mandate_registry_mock.go
ledger-core/v2/network/consensus/gcpv2/api/profiles/active_node_mock.go
ledger-core/v2/network/consensus/gcpv2/api/profiles/base_node_mock.go
ledger-core/v2/network/consensus/gcpv2/api/profiles/candidate_profile_mock.go
ledger-core/v2/network/consensus/gcpv2/api/profiles/host_mock.go
ledger-core/v2/network/consensus/gcpv2/api/profiles/local_node_mock.go
ledger-core/v2/network/consensus/gcpv2/api/profiles/static_profile_extension_mock.go
ledger-core/v2/network/consensus/gcpv2/api/profiles/static_profile_mock.go
ledger-core/v2/network/consensus/gcpv2/api/proofs/cloud_state_hash_mock.go
ledger-core/v2/network/consensus/gcpv2/api/proofs/globula_state_hash_mock.go
ledger-core/v2/network/consensus/gcpv2/api/proofs/member_announcement_signature_mock.go
ledger-core/v2/network/consensus/gcpv2/api/proofs/node_state_hash_evidence_mock.go
ledger-core/v2/network/consensus/gcpv2/api/proofs/node_state_hash_mock.go
ledger-core/v2/network/consensus/gcpv2/api/transport/full_introduction_reader_mock.go
ledger-core/v2/network/consensus/gcpv2/api/transport/packet_parser_mock.go
ledger-core/v2/vanilla/cryptkit/cert.go
ledger-core/v2/vanilla/cryptkit/data_signer_mock.go
ledger-core/v2/vanilla/cryptkit/digest.go
ledger-core/v2/vanilla/cryptkit/digest_holder_mock.go
ledger-core/v2/vanilla/cryptkit/digest_signer_mock.go
ledger-core/v2/vanilla/cryptkit/keystore.go
ledger-core/v2/vanilla/cryptkit/signature.go
ledger-core/v2/vanilla/cryptkit/signature_holder_mock.go
ledger-core/v2/vanilla/cryptkit/signature_key_holder_mock.go

PLAT-139: fix paths in cryptkit mocks

---

ledger-core/v2/logicrunner/s_contract_runner/contract_runner.go
ledger-core/v2/logicrunner/sm_object/object.go

HOTFIX: fix typos in logicrunner code

---

ledger-core/v2/log/adapters/zlog/adapter_test.go
ledger-core/v2/log/global/struct_log_test.go
ledger-core/v2/log/logoutput/log_entry_info.go

Fix tests depended on line numbers

Plat-146 fix log line tests

---

ledger-core/v2/instrumentation/inslogger/sourceinfo_test.go

Got rid of line number constant

PLAT-146: removed line number constant in getCallInfo

---

README.md

add README.md with initial instruction

start writing README.md

---

ledger-core/v2/application/api/requester/requester_test.go
ledger-core/v2/conveyor/pulse_manager_test.go
ledger-core/v2/ledger-v2/dropbag/vermap/map.go
ledger-core/v2/ledger-v2/smachines/drop.go
ledger-core/v2/log/global/struct_log_test.go
ledger-core/v2/vanilla/keyset/keyset_test.go

Hotfix fix tests

---

ledger-core/v2/application/api/functest_contract.go
ledger-core/v2/application/testutils/launchnet/launchnet.go

Functests still do not work, but at least network starts

NOISSUE: fix launchnet start

---

ledger-core/v2/README.md

change golang version from 12 to 14 in README

PLAT-192: change golang version from 12 to 14

---

ledger-core/v2/README.md

Add make vendor before build binary

NOISSUE: Update readme

---

ledger-core/v2/go.mod

Add lost update of gotestsum to go.mod

Add lost update of gotestsum to go.mod

---

ledger-core/v2/application/builtin/contract/testwallet/testwallet.go
ledger-core/v2/application/builtin/contract/testwallet/testwallet.wrapper.go
ledger-core/v2/application/builtin/proxy/testwallet/testwallet.go

add Balance and Accept methods
add code and regen builtin
wait for func tests

PLAT-205 [feature] inner methods for testwallet

---

ledger-core/v2/application/functest/api_test_utils.go
ledger-core/v2/application/functest/create_wallet_test.go
ledger-core/v2/application/functest/structures.go
ledger-core/v2/go.mod

add test for wallet/create; add api test-utils for tests

PLAT-203: functest for wallet/create

---

ledger-core/v2/application/builtin/contract/testwallet/testwallet.go
ledger-core/v2/application/builtin/contract/testwallet/testwallet.wrapper.go
ledger-core/v2/application/builtin/proxy/testwallet/testwallet.go

add Transfer method that calls another testwallet
wrote method, ran ./bin/insgocc regen-builtin  
wait for functests

PLAT-214 [feature] add method that calls contract

---

ledger-core/v2/log/global/log_global.go
ledger-core/v2/vanilla/throw/throwables.go

copy-paste text message fix for throw.Impossible()
global.Fatalm()

NOISSUE-logger fix

---

.github/workflows/common.yaml
ledger-core/v2/go.mod
ledger-core/v2/scripts/gitstatus.sh
ledger-core/v2/testutils/network/gateway_mock.go

This step checks that no tracked files have changed in the repository after `make vendor pre-build build`
* Added script that checks if the working directory is clean
* Added this checker to GH Actions after the build step

PLAT-240: tracked files checker

---

ledger-core/v2/application/functest/api_test_utils.go
ledger-core/v2/application/functest/structures.go
ledger-core/v2/application/functest/wallet_add_amount_test.go
ledger-core/v2/application/functest/wallet_create_test.go
ledger-core/v2/application/functest/wallet_get_balance_test.go

add tests to check response fields, add tests to check concurrent requests

PLAT-207: add /wallet/add_amount, /wallet/get_balance tests

---

ledger-core/v2/application/functest/api_test_utils.go
ledger-core/v2/application/functest/structures.go
ledger-core/v2/application/functest/wallet_create_test.go
ledger-core/v2/application/functest/wallet_get_balance_test.go
ledger-core/v2/application/functest/wallet_transfer_test.go

**The test fails now, due to mock API.**

PLAT-216: add /wallet/transfer functest

---

ledger-core/v2/application/bootstrap/bootstrap.go

generate empty boostrap config fixing functests

PLAT-246: generate empty boostrap config fixing functests

---

.github/workflows/common.yaml
ledger-core/v2/Makefile

Added functests step to `common.yaml` workflow

PLAT-260: functests on CI

---

ledger-core/v2/configuration/configuration_test.go
ledger-core/v2/configuration/testdata/changed.yml
ledger-core/v2/configuration/testdata/default.yml

NOISSUE fixed false success tests in testmain

---

README.md

Add codecov.io badge to README + minor changes.

NOISSUE: add codecov.io badge to README + minor changes.

---

.github/workflows/all-checks.yaml
README.md

This PR adds a nice "all-checks:passed" (or "all-checks:faled") badge to README

NOISSUE: Add "all-checks:passed" badge to README

---

ledger-core/v2/Makefile.testing
ledger-core/v2/application/functest/wallet_add_amount_test.go
ledger-core/v2/application/functest/wallet_get_balance_test.go
ledger-core/v2/application/functest/wallet_scenarios_test.go

Add test for update wallet balance; add test for different concurrent requests on wallet
**Tests fail now!**

PLAT-207: two test for happy-path

---

ledger-core/v2/application/functest/api_test_utils.go
ledger-core/v2/application/functest/structures.go
ledger-core/v2/application/functest/wallet_get_balance_test.go
ledger-core/v2/application/functest/wallet_scenarios_test.go
ledger-core/v2/application/functest/wallet_transfer_test.go

NOISSUE: add const for initialBalance in tests

---

ledger-core/v2/README.md
ledger-core/v2/cmd/insolard/commands.go

- descriptions and correct flags  for CLI commands
- readme update, run node guide in production mode

PLAT-182: all insolard CLI commands

---

ledger-core/v2/virtual/object/object.go

Add counters of pending execution to object state
Add fields to struct `Info`
This counters must be filled when processing VStateReport (PLAT-210)

PLAT-276: counters of pending execution

---

ledger-core/v2/vanilla/unsafekit/byte_string.go

This is a kinda ugly replacement, but it makes compiler happy.

PLAT-292: fix another checkptr problem

---

.github/workflows/all-checks.yaml
ledger-core/v2/Makefile.testing

Don't run unit tests twice on CI.

PLAT-303: dont run unit tests twice on CI

---

ledger-core/v2/scripts/insolard/launchnet.sh

Added 'headless' parameter for launchnet.sh
Changed launchnet.sh
Run in terminal (root directory): 
```
./scripts/insolard/launchnet.sh -g headless 
```

PLAT-143: Add headless parameter for launchnet.sh

---

ledger-core/v2/conveyor/smachine/api_shared_link.go
ledger-core/v2/virtual/execute/execute.go
ledger-core/v2/virtual/object/object.go

Increment pending counters when processing new message
Add increment code to SMExecute.stepWaitObjectReady

Plat 278 update pending counters in incoming requests

---

.github/workflows/all-checks.yaml

Add nodes output to artifacts after running functests.

NOISSUE: add nodes output to artifacts after running functests

---

ledger-core/v2/conveyor/sm_future_event.go
ledger-core/v2/conveyor/smachine/api_context.go
ledger-core/v2/conveyor/smachine/api_logger.go
ledger-core/v2/conveyor/smachine/api_state_machine.go
ledger-core/v2/conveyor/smachine/api_step.go
ledger-core/v2/conveyor/smachine/exec_adapter_call.go
ledger-core/v2/conveyor/smachine/slot.go
ledger-core/v2/conveyor/smachine/slot_aliases.go
ledger-core/v2/conveyor/smachine/slot_bargein.go
ledger-core/v2/conveyor/smachine/slot_machine.go
ledger-core/v2/conveyor/smachine/slot_machine_execute.go
ledger-core/v2/conveyor/smachine/slot_machine_migrate.go
ledger-core/v2/conveyor/smachine/slot_prepare.go
ledger-core/v2/conveyor/smachine/state_update_type.go
ledger-core/v2/conveyor/smachine/state_updates.go

Performance improvement by short-looping of steps
Support of delayed replies by adapter
Minor refactoring, removal of an unused field and fixes to comments

NOISSUE-conveyor-improvements-2

---

.github/workflows/all-checks.yaml

Quick fix of "file changed as we read it" problem, originally proposed by Kirill.

NOISSUE: quick fix of "file changed as we read it" problem

---

ledger-core/v2/virtual/handlers/handle_meta.go
ledger-core/v2/virtual/handlers/vcallrequest.go
ledger-core/v2/virtual/handlers/vcallresult.go
ledger-core/v2/virtual/handlers/vstatereport.go
ledger-core/v2/virtual/handlers/vstaterequest.go
ledger-core/v2/virtual/handlers/vstateunavailable.go
ledger-core/v2/virtual/virtual.go

PLAT-301: renamed requests to handlers

---

.github/workflows/all-checks.yaml
ledger-core/v2/conveyor/smachine/api_panic.go
ledger-core/v2/log/global/log_global.go
ledger-core/v2/logicrunner/statemachine/logger.go
ledger-core/v2/server/internal/virtual/components_test.go
ledger-core/v2/vanilla/throw/chain.go
ledger-core/v2/vanilla/throw/minimizer.go
ledger-core/v2/vanilla/throw/minimizer_test.go
ledger-core/v2/vanilla/throw/stackcmp_test.go
ledger-core/v2/vanilla/throw/stacktrace.go
ledger-core/v2/vanilla/throw/stackwrap.go
ledger-core/v2/vanilla/throw/wraps.go
ledger-core/v2/virtual/integration/convlog/default_convlog.go
ledger-core/v2/virtual/integration/convlog/default_others.go
ledger-core/v2/virtual/integration/convlog/logger.go
ledger-core/v2/virtual/integration/utils/server.go
ledger-core/v2/virtual/statemachine/logger.go
ledger-core/v2/virtual/virtual.go

- added convlogtxt build tag to activate human-readable console logger for SMs 
- added human-readable console logger for SMs 
- added stack trace minimization tools to throw
- added stack trace minimization to both SM loggers
- and improved a bit tooling of throw

PLAT-284 friendly panic logging in SMs

---

ledger-core/v2/configuration/ledger.go
ledger-core/v2/configuration/testdata/changed.yml
ledger-core/v2/configuration/testdata/default.yml
ledger-core/v2/scripts/generate_insolar_configs.go

keep one option, it's still used in jet coordinator, we will deal later
at some point

delete most of ledger's config since we deleted ledger itself

---

ledger-core/v2/pulse/pulse_number.go
ledger-core/v2/reference/encoder.go

- functions to check package-private pulse numbers

NOISSUE Package-private pulse numbers

---

ledger-core/v2/application/genesis.go
ledger-core/v2/application/genesisrefs/refs.go
ledger-core/v2/application/testwalletapi/statemachine/statemachine.go
ledger-core/v2/insolar/gen/reference.go
ledger-core/v2/ledger-v2/dropbag/refmap/semimap_values_test.go
ledger-core/v2/logicrunner/builtin/builtin.go
ledger-core/v2/logicrunner/goplugin/ginsider/ginsider.go
ledger-core/v2/reference/compact.go
ledger-core/v2/reference/decoder_test.go
ledger-core/v2/reference/encoder.go
ledger-core/v2/reference/encoder_test.go
ledger-core/v2/reference/global.go
ledger-core/v2/reference/global_test.go
ledger-core/v2/reference/marshal_test.go
ledger-core/v2/runner/executor/goplugin/ginsider/ginsider.go
ledger-core/v2/virtual/execute/execute.go
ledger-core/v2/virtual/handlers/vcallresult.go
ledger-core/v2/virtual/integration/method_test.go
ledger-core/v2/virtual/integration/object_test.go
ledger-core/v2/virtual/integration/stateunavailable_test.go

* Corrected use of references
* Refinements of reference methods

Corrected use of references

---

ledger-core/v2/conveyor/pulse_slot.go
ledger-core/v2/virtual/execute/execute.go
ledger-core/v2/virtual/execute/update_pending_counters_test.go
ledger-core/v2/virtual/integration/mock/publisher.go
ledger-core/v2/virtual/integration/pending_counters_test.go
ledger-core/v2/virtual/integration/utils/server.go

Move updating counters as early as we can
Refactor code and call updating counters after Init step
Run test

PLAT-278: pending counters must be updated after init

---

ledger-core/v2/insolar/payload/requestcontent_test.go
ledger-core/v2/insolar/payload/requestedcontent.go
ledger-core/v2/virtual/integration/object_test.go
ledger-core/v2/virtual/object/object.go

set all object flags upon state request. We can work only if VE has full object stat

PLAT-198: pass all object flags upon state request

---

.github/workflows/linux-checks.yaml
.github/workflows/windows-checks.yaml

Split Linux and Windows workflow files.

NOISSUE: split linux and windows workflows

---

ledger-core/v2/insolar/defaults/defaults_test.go

PLAT-333: fix TestDefaults on Windows

---

README.md

Update badges in README.md. We don't have all-checks any more, there are linux-checks and windows-checks.

NOISSUE: update badges in README.md

---

ledger-core/v2/application/testwalletapi/statemachine/statemachine.go
ledger-core/v2/insolar/gen/reference.go
ledger-core/v2/runner/executor/builtin/proxyhelper.go
ledger-core/v2/runner/executor/common/proxyctx.go
ledger-core/v2/runner/executor/common/rpctypes/rpctypes.go
ledger-core/v2/runner/executor/goplugin/ginsider/ginsider.go
ledger-core/v2/runner/runner_rpc.go
ledger-core/v2/virtual/integration/method_api_test.go
ledger-core/v2/virtual/integration/method_test.go
ledger-core/v2/virtual/integration/statereport_test.go
ledger-core/v2/virtual/integration/staterequest_test.go
ledger-core/v2/virtual/integration/stateunavailable_test.go
ledger-core/v2/virtual/integration/utils/server.go

PLAT-335: re-enable fixed scenario test for Windows

---

ledger-core/v2/conveyor/pulse_slot.go

Methods to access current pulse number and data

Methods to access current pulse number and data

---

ledger-core/v2/application/testwalletapi/handlers.go
ledger-core/v2/virtual/integration/constructor_api_test.go
ledger-core/v2/virtual/integration/constructor_test.go
ledger-core/v2/virtual/integration/method_api_test.go
ledger-core/v2/virtual/integration/method_test.go
ledger-core/v2/virtual/integration/object_test.go
ledger-core/v2/virtual/integration/statereport_test.go
ledger-core/v2/virtual/integration/staterequest_test.go
ledger-core/v2/virtual/integration/stateunavailable_test.go
ledger-core/v2/virtual/integration/utils/server_http.go

I've added timeout for all API integration tests, and added timeout for one of tests that could freeze in case of panic

NOISSUE: implement timeouts for API

---

.github/workflows/linux-checks.yaml
ledger-core/v2/scripts/gitstatus.sh

* Added protobuf generation to build step
* Added verbose diff output to check step

NOISSUE: check protobuf generation diffs

---

ledger-core/v2/conveyor/smachine/api_context.go
ledger-core/v2/conveyor/smachine/context_exec.go
ledger-core/v2/conveyor/smachine/example/main/main_test.go
ledger-core/v2/conveyor/smachine/execution_context_mock.go

* Use narrower ConditionalBuilder instead of StateConditionalBuilder when the last one is irrelevant
* Use Player example as a small test

NOISSUE-corrected-wait-builder

---

ledger-core/v2/Makefile.build

Fix clean build launchnet
Fix makefile for build pulsewatcher in `build` target
run make build

NOISSUE: Fix build pulsewatcher in build target

---

ledger-core/v2/instrumentation/inslogger/caller_ext_test.go
ledger-core/v2/instrumentation/inslogger/caller_test.go
ledger-core/v2/instrumentation/inslogger/inslogger_ext_test.go

Fix test of inslogger for run it when project src dir outside from GOPATH
Fix paths regexp
Run `make test_all`

NOISSUE: fix tests for project dir outside from GOPATH

---

ledger-core/v2/runner/adapter.go
ledger-core/v2/runner/runner.go
ledger-core/v2/runner/worker.go

Also add support for error reporting in Runner's worker

NOISSUE: reintroduce Runner.ExecutionClassify stub function

---

ledger-core/v2/conveyor/smachine/api_logger.go
ledger-core/v2/instrumentation/inslogger/log_cfg_test.go
ledger-core/v2/instrumentation/inslogger/test_helper.go
ledger-core/v2/log/adapters/bilog/adapter_test.go
ledger-core/v2/log/adapters/zlog/builder.go
ledger-core/v2/log/global/log_global.go
ledger-core/v2/log/logcommon/redirector.go

* logger comments 
* test logger fix

NOIISUE: logger comments and test logger fix

---

ledger-core/v2/instrumentation/inslogger/console_printer.go
ledger-core/v2/instrumentation/inslogger/console_printer_tag.go
ledger-core/v2/scripts/insolard/launchnet.sh
ledger-core/v2/virtual/handlers/handle_meta.go
ledger-core/v2/virtual/statemachine/dispatcher.go
ledger-core/v2/virtual/statemachine/logger.go

1. fix wrong error logging 
2. add tags to launchnet.sh to use good logger

PLAT-358: fix error logging

---

.github/workflows/linux-checks.yaml
.github/workflows/windows-checks.yaml

Added Slack notifications on CI job failure

NOISSUE: Add CI failure notifications to Slack

---

.github/workflows/linux-checks.yaml
.github/workflows/windows-checks.yaml

NOISSUE: send notifications only from master

---

ledger-core/v2/insolar/contract/virtual.go
ledger-core/v2/insolar/payload/vcallrequestflags.go
ledger-core/v2/insolar/payload/vcallrequestflags_test.go
ledger-core/v2/virtual/execute/execute_isolation_negotiation_test.go
ledger-core/v2/virtual/execute/execute_test.go
ledger-core/v2/virtual/integration/method_test.go

more precise call flags realization and tooling

PLAT-326: callflags better tooling

---

ledger-core/v2/virtual/execute/execute_isolation_negotiation_test.go

better unit test for single step of SMExecute
used table testing for a lot of cases
run tests

PLAT-329: small unit test for single step purpose

---

ledger-core/v2/virtual/object/object.go
ledger-core/v2/virtual/object/pending_table.go
ledger-core/v2/virtual/object/pending_table_test.go

add pending table struct
run tests

PLAT-295 penging table struct

---

ledger-core/v2/instrumentation/inslogger/inslogger.go
ledger-core/v2/instrumentation/inslogger/test_helper.go
ledger-core/v2/instrumentation/inslogger/test_helper_test.go
ledger-core/v2/log/logcommon/redirector.go
ledger-core/v2/virtual/integration/constructor_api_test.go
ledger-core/v2/virtual/integration/convlog/logger.go
ledger-core/v2/virtual/integration/delegated_finished_test.go
ledger-core/v2/virtual/integration/object_test.go
ledger-core/v2/virtual/integration/statereport_test.go
ledger-core/v2/virtual/integration/stateunavailable_test.go
ledger-core/v2/virtual/integration/utils/server.go
ledger-core/v2/virtual/object/catalog.go

* Proper handling of error and fatal logs in tests - test will fail
* Fix for error when replacing TraceID for SMObject

NOISSUE: fix test logs

---

ledger-core/v2/virtual/object/pending_table.go

change pointer on struct to bool type
run tests

PLAT-295 remove pointer

---

ledger-core/v2/conveyor/smachine/api_logger.go
ledger-core/v2/conveyor/smachine/slot.go
ledger-core/v2/conveyor/smachine/slot_machine_execute.go
ledger-core/v2/conveyor/smachine/slot_machine_migrate.go

NOISSUE: Short-loop was not logged

---

ledger-core/v2/conveyor/conveyor_test.go

* Added wait to stop, to avoid racing with leak detection

NOISSUE: Test stability fix

---

ledger-core/v2/conveyor/smachine/slot_machine.go
ledger-core/v2/conveyor/smachine/slot_machine_execute.go
ledger-core/v2/conveyor/smachine/slot_machine_migrate.go
ledger-core/v2/conveyor/smachine/slot_pool.go

* Fix for race between AllocateSlot and ScanAndCleanup (ScanAndCleanup has ignored mutex )

NOISSUE: fix SlotPool race

---

.github/workflows/linux-checks.yaml
ledger-core/v2/Makefile.testing

Build, where steps weren't skipped - https://github.com/insolar/assured-ledger/runs/706228872
In the first commit steps were run, in the second commit - skipped.

PLAT-349: add github-actions for testrail integration

---

ledger-core/v2/testutils/convlog_test/convloglevels.go
ledger-core/v2/virtual/statemachine/logger_step_test.go

* improved test to ensure that Fatal is preserved

NOISSUE: test to check preservation of Fatal

---

ledger-core/v2/virtual/object/object.go
ledger-core/v2/virtual/object/object_migration_test.go

Send VStateReport once and stop SMObject when it sent state and has no pending executions
Increment counter when sent VStateReport and check it in stepWaitIndefinitely
Run test

PLAT-372: Stop SMObject when it sent state and has no pending execs

---

ledger-core/v2/log/adapters/bilog/adapter_test.go
ledger-core/v2/log/adapters/zlog/adapter_test.go
ledger-core/v2/log/adapters/zlog/builder.go

* zlog adapter looses settings when WithoutInheritedFields() is applied
* tests improved

NOISSUE: Fix for zlog loosing settings

---

ledger-core/v2/virtual/handlers/vstaterequest.go
ledger-core/v2/virtual/object/object.go

- fill VStateReport in one place
- fix bug with VStateRequest handler was not filling state properly
moved build report into SMObject Info
run tests

PLAT-311: fill VStateReport in one place

---

ledger-core/v2/virtual/object/pending_table.go
ledger-core/v2/virtual/object/pending_table_test.go

recalculate oldest pulse on pending finished
run tests

PLAT-311: recalculate oldest pulse on pending finished

---

ledger-core/v2/virtual/handlers/vdelegatedrequestfinished.go
ledger-core/v2/virtual/handlers/vdelegatedrequestfinished_test.go

Update pending table in VDelegatedRequestFinished
Call `Finish` for table
Run test

PLAT-312: Update pending table in VDelegatedRequestFinished

---

ledger-core/v2/virtual/execute/execute.go
ledger-core/v2/virtual/execute/execute_test.go
ledger-core/v2/virtual/object/object.go
ledger-core/v2/virtual/object/pending_table.go
ledger-core/v2/virtual/object/pending_table_test.go

- knownrequests should be tabled by tolerance
- earliestPulse for each path should be calculated according to tables
run tests

PLAT-311: earliest request pulse fillage

---

ledger-core/v2/conveyor/smachine/api_context.go
ledger-core/v2/conveyor/smachine/context_basic.go
ledger-core/v2/conveyor/smachine/context_exec.go
ledger-core/v2/conveyor/smachine/migration_context_mock.go
ledger-core/v2/conveyor/smachine/state_updates.go
ledger-core/v2/go.mod
ledger-core/v2/pulse/special_pulse_numbers.go

* Enable CallSubroutine on migrate

NOISSUE: CallSubroutine on migrate

---

ledger-core/v2/testutils/debuglogger.go

thanks to @bigbes - we've found race in debuglogger continue call

PLAT-428: fix in debug logger continue

---

ledger-core/v2/conveyor/smachine/context_share_publish.go
ledger-core/v2/conveyor/smachine/context_share_publish_test.go

* fix for proper behavior of GetGlobalPublished without global registry

NOISSUE: fix global published

---

ledger-core/v2/server/internal/virtual/components.go
ledger-core/v2/virtual/handlers/vdelegatedcallrequest.go
ledger-core/v2/virtual/handlers/vdelegatedcallrequest_test.go
ledger-core/v2/virtual/integration/utils/server.go
ledger-core/v2/virtual/token/service.go
ledger-core/v2/virtual/virtual.go

added token service to prevent jetAffinityHelper usage inside handler SMs
run tests

PLAT-425: service for tokens

---

ledger-core/virtual/execute/execute.go
ledger-core/virtual/object/object.go

update finished requests in known requests map so earliest request pulse would be appropriate

PLAT-311: update knownRequests table upon finished requests processing

---

.github/workflows/linux-checks.yaml
.github/workflows/master-checks.yaml
.github/workflows/windows-checks.yaml

Upload integration_test.log to artifacts

PLAT-440: upload integration_test.log to artifacts

---

ledger-core/conveyor/conveyor.go
ledger-core/virtual/integration/delegated_finished_test.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/statemachine/worker.go
ledger-core/virtual/virtual.go

* cycle callback for conveyor worker
* instrumentation for test server
* improved test

NOISSUE: predictable tests

---

ledger-core/conveyor/smachine/main/example/catalogC.plantuml
ledger-core/conveyor/smachine/main/example/example_1.plantuml
ledger-core/conveyor/smachine/main/example/example_2.plantuml
ledger-core/conveyor/smachine/main/example/sm_vm_call_req.plantuml
ledger-core/conveyor/smachine/main/example/sm_vm_object.plantuml
ledger-core/go.mod
ledger-core/virtual/execute/execute.plantuml
ledger-core/virtual/handlers/vdelegatedcallrequest.plantuml
ledger-core/virtual/handlers/vdelegatedrequestfinished.plantuml
ledger-core/virtual/handlers/vstatereport.plantuml
ledger-core/virtual/handlers/vstaterequest.plantuml

Regenerate UMLs, deterministic ordered steps
Change dependency to new utility version and 
run: 
make generate 
run **make generate** several times and check that you will not have changes from run to run.
Fix sort in utility
https://github.com/insolar/sm-uml-gen/commit/9d410c3b8b3d126de743c888dd925f0ed8c241b1

NOISSUE: Re-generated UMLs

---

ledger-core/virtual/execute/execute.go
ledger-core/virtual/object/object.go

- simplify execute step save new object 
- simplify SMObject finished request

PLAT-419: improvement

---

ledger-core/virtual/handlers/vdelegatedcallrequest_test.go

PLAT-423: interference tests

---

ledger-core/virtual/execute/execute.go
ledger-core/virtual/execute/execute.plantuml
ledger-core/virtual/integration/delegated_finished_test.go
ledger-core/virtual/object/object.go

Prevent updating of object shared state if pulse was changed

PLAT-419: don't update objest.State if pulse was changed

---

ledger-core/virtual/integration/delegated_finished_test.go
ledger-core/virtual/integration/utils/server.go

* less lines to use conveyor wait in tests

NOISSUE: Conveyor wait improvement

---

README.md

consensus-checks are also executed regularly on master branch.

NOISSUE: add consensus-checks badge to README.md

---

ledger-core/instrumentation/inslogger/test_helper.go
ledger-core/virtual/integration/delegated_finished_test.go
ledger-core/virtual/integration/method_test.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/vstatereport_test.go

NOISSUE: integration test server helpers and test fixes

---

ledger-core/instrumentation/inslogger/test_helper.go

NOISSUE: revert text logs in local runs

---

ledger-core/virtual/object/info_test.go
ledger-core/virtual/object/object.go

NOISSUE: fix GetEarliestPulse with test

---

ledger-core/virtual/integration/vdelegated_test.go

NOISSUE: unstable test, need to think and change

---

ledger-core/Makefile.testing

Use pkill instead of pgrep+xargs kill

NOISSUE: use pkill instead of pgrep+xargs kill

---

ledger-core/virtual/handlers/vdelegatedcallrequest.go
ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
ledger-core/virtual/token/service.go

PLAT-311: fill token outgoing reference for matching on other side

---

ledger-core/Makefile.testing

fix make test_func
move hack from test_func_slow to test_func

test_func doesn't start without trick, used in test_func_slow

---

ledger-core/insolar/payload/proto_vnvn.r0.pb.go
ledger-core/insolar/payload/proto_vnvn.r0.proto
ledger-core/virtual/execute/delegatedtokenrequest.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/handlers/vdelegatedcallrequest.go
ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
ledger-core/virtual/integration/vdelegated_test.go

- removed signature fields
- updated Delegated request/response according to spec

NOISSUE: DelegatedToken protobuf cleanup

---

ledger-core/log/adapters/bilog/adapter.go
ledger-core/log/adapters/bilog/json/encoder.go
ledger-core/log/adapters/bilog/msgencoder/api.go
ledger-core/log/adapters/bilog/pbuf/encoder.go
ledger-core/log/adapters/bilog/text/encoder.go

* removed level filtering for stack trace
* fix missing space on context merge for text output of bilog

NOISSUE: missing stack and space

---

ledger-core/conveyor/conveyor.go
ledger-core/conveyor/conveyor_test.go
ledger-core/conveyor/pulse_cache.go
ledger-core/conveyor/pulse_manager.go
ledger-core/conveyor/pulse_manager_test.go
ledger-core/conveyor/sm_antique_event.go
ledger-core/pulse/pulse_range.go
ledger-core/pulse/pulse_range_test.go

* Access to conveyor cache
* Change cache to store pulse.Range instead of pulse.Data
* Convenience functions to get prev pulse data

PLAT-451: Access to conveyor cache

---

ledger-core/testutils/runner/logicless/service.go
ledger-core/virtual/integration/constructor_test.go
ledger-core/virtual/integration/delegated_finished_test.go
ledger-core/virtual/integration/method_test.go
ledger-core/virtual/integration/object_test.go
ledger-core/virtual/integration/statereport_test.go
ledger-core/virtual/integration/staterequest_test.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/vdelegated_test.go
ledger-core/virtual/integration/vstatereport_test.go
ledger-core/virtual/statemachine/logger_machine.go

* move to typedChecker instead of raw function
* move to serviceMock instead of mocking separate components (partially)

NOISSUE: massive refactor of tests

---

ledger-core/conveyor/conveyor.go
ledger-core/conveyor/smachine/api_worker.go
ledger-core/conveyor/smachine/context_worker_wrapper.go
ledger-core/conveyor/sworker/worker_simple.go
ledger-core/virtual/integration/utils/server.go

* Detection of in-cycle activities by WaitActiveThenIdleConveyor

NOISSUE: Detect in-cycle activities by WaitActiveThenIdleConveyor

---

ledger-core/insolar/payload/stringer_test.go
ledger-core/reference/global.go
ledger-core/reference/local.go
ledger-core/rms/binary_raw.go
ledger-core/rms/record_body.go
ledger-core/rms/reference.go
ledger-core/rms/serializable.go

* fenced out by implementing MarshalText

NOISSUE: Prevent gogo stringer from failing on private fields

---

ledger-core/application/testwalletapi/statemachine/statemachine.plantuml
ledger-core/conveyor/smachine/main/example/catalogC.plantuml
ledger-core/conveyor/smachine/main/example/example_1.plantuml
ledger-core/conveyor/smachine/main/example/example_2.plantuml
ledger-core/conveyor/smachine/main/example/example_3.plantuml
ledger-core/conveyor/smachine/main/example/sm_vm_call_req.plantuml
ledger-core/conveyor/smachine/main/example/sm_vm_object.plantuml
ledger-core/go.mod
ledger-core/virtual/execute/execute.plantuml
ledger-core/virtual/handlers/vcallrequest.plantuml
ledger-core/virtual/handlers/vcallresult.plantuml
ledger-core/virtual/handlers/vdelegatedcallrequest.plantuml
ledger-core/virtual/handlers/vdelegatedcallresponse.plantuml
ledger-core/virtual/handlers/vdelegatedrequestfinished.plantuml
ledger-core/virtual/handlers/vstatereport.plantuml
ledger-core/virtual/handlers/vstaterequest.plantuml
ledger-core/virtual/object/finalizedstate/statefinalizer.plantuml

NOISSUE: regenerated umls

---

ledger-core/conveyor/conveyor.go
ledger-core/conveyor/sm_pulse_slot.go
ledger-core/conveyor/smachine/slot_machine_queue.go
ledger-core/vanilla/atomickit/uint32.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/virtual.go

* change event to state model for WaitActiveThenIdleConveyor
* disabled eventless sleep for test
* removed polling for past slots

NOISSUE: Prevent mis-fire by WaitActiveThenIdleConveyor

---

ledger-core/application/testwalletapi/statemachine/statemachine.plantuml
ledger-core/conveyor/smachine/main/example/catalogC.plantuml
ledger-core/conveyor/smachine/main/example/example_1.plantuml
ledger-core/conveyor/smachine/main/example/example_2.plantuml
ledger-core/conveyor/smachine/main/example/example_3.plantuml
ledger-core/conveyor/smachine/main/example/sm_vm_call_req.plantuml
ledger-core/conveyor/smachine/main/example/sm_vm_object.plantuml
ledger-core/go.mod
ledger-core/virtual/execute/execute.plantuml
ledger-core/virtual/handlers/vcallrequest.plantuml
ledger-core/virtual/handlers/vcallresult.plantuml
ledger-core/virtual/handlers/vdelegatedcallrequest.plantuml
ledger-core/virtual/handlers/vdelegatedcallresponse.plantuml
ledger-core/virtual/handlers/vdelegatedrequestfinished.plantuml
ledger-core/virtual/handlers/vstatereport.plantuml
ledger-core/virtual/handlers/vstaterequest.plantuml
ledger-core/virtual/object/finalizedstate/statefinalizer.plantuml

* call to adapters (both inline and delayed)
* indicate migrations in transitions

NOISSUE: better umls

---

ledger-core/conveyor/conveyor_test.go
ledger-core/conveyor/conveyor_test.plantuml
ledger-core/conveyor/main/conveyor_test_main.go
ledger-core/conveyor/main/conveyor_test_main.plantuml
ledger-core/conveyor/sm_antique_event.go
ledger-core/conveyor/sm_antique_event.plantuml
ledger-core/conveyor/sm_future_event.go
ledger-core/conveyor/sm_future_event.plantuml
ledger-core/conveyor/sm_pulse_slot.go
ledger-core/conveyor/sm_pulse_slot.plantuml
ledger-core/conveyor/smachine/example/player.go
ledger-core/conveyor/smachine/example/player.plantuml
ledger-core/virtual/object/object.go
ledger-core/virtual/object/object.plantuml

PLAT-442: Unmute UML generation

---

ledger-core/virtual/integration/method_test.go

C5086 | Вызов ordered метода контракта B из ordered метода контракта A  
C5087 | Вызов unordered метода контракта B из ordered метода контракта A

PLAT-463: A.Foo -> B.Bar tests

---

ledger-core/virtual/execute/execute.go
ledger-core/virtual/execute/execute_isolation_negotiation_test.go
ledger-core/virtual/integration/method_test.go

PLAT-478: fix negotiation of isolation calls

---

ledger-core/virtual/handlers/vdelegatedcallrequest_test.go

PLAT-482: add cases in test

---

.github/workflows/consensus-checks.yaml
ledger-core/go.mod
ledger-core/scripts/deploy/kube-deploy-tool/config.yaml
ledger-core/scripts/deploy/kube-deploy-tool/configuration.go
ledger-core/scripts/deploy/kube-deploy-tool/consensus-test-callbacks.go
ledger-core/scripts/deploy/kube-deploy-tool/kube-deploy-tool.go
ledger-core/scripts/deploy/kube-deploy-tool/metricsreport.go

* Embedded `metricreplicator` and `report` tools usage into `kube-deploy-tool`
* Started creating reports automatically in GHA

PLAT-253: consensus performance reports

---

.github/codecov.yml
.github/workflows/linux-checks.yaml
.github/workflows/master-checks.yaml

Codecov is somehow ignoring the ignore section of codecov.yml. This is an attempt to fix it.

NOISSUE: fix codecov

---

ledger-core/Makefile.testing

- use text output in all test runs
- test run outputs both to console and file
- removed -json test output
- added -v for verbose test logs
see checks output

PLAT-477: text test run output and testrail cli update

---

ledger-core/conveyor/conveyor_test.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/vstatereport_test.go

table test that covers many variouse situations

PLAT-471: test pending counters and earliest pulses in VStateReport

---

ledger-core/instrumentation/inslogger/logwatermill/watermill_adapter.go

* Report stack for errors from watermill

NOISSUE: Report stack for errors from watermill

---

ledger-core/runner/runner.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/execute/execute.plantuml
ledger-core/virtual/integration/method_test.go

- marshalled error result for outgoing call isolation violation

PLAT-374: return error result upon outoing call isolation violation

---

ledger-core/virtual/integration/method_test.go

Test SMExecute send request to runner with right object state (validated and dirty)
Add 2 test
run test

PLAT-542: test executor send right object state to runner

---

ledger-core/virtual/object/object.go
ledger-core/virtual/object/object.plantuml
ledger-core/virtual/object/object_migration_test.go

Fix send VStateReport if object state is Empty and no pending counters 
Remove wrong condition in migration
run tests

PLAT-556: Fix send VStateReport if object state is Empty and no pendings

---

ledger-core/testutils/synchronization/point.go
ledger-core/virtual/integration/deduplication_test.go

(backported from future PR for test)

NOISSUE: redo synchronization point

---

ledger-core/conveyor/smachine/context_share_publish_test.go
ledger-core/conveyor/smachine/slot_aliases.go

* fix for first alias being missed

PLAT-581: Fix alias cleanup

---

ledger-core/virtual/handlers/handle_meta.go
ledger-core/virtual/handlers/vfindcallrequest.go
ledger-core/virtual/handlers/vfindcallrequest.plantuml
ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go

- added VFindCallRequest handler
- unskip integration tests for this handler, thanks @ruz 
run tests

PLAT-389: vfindcallrequest handler and test unskip

---

ledger-core/virtual/execute/execute_test.go

Test executor will stop without sending messages if migrate before outgoing call
Add SMExecute to slotdebugger, run it til stepStartRequestProcessing and call migration. Wait while machine done execution and MessageSender have no errors
Write test
run test

PLAT-520: executor stop without sending messages if migrate before outgoing call

---

ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go

Fixed leaking SMs after test is finished:
1. we need to ensure all async calls are done
2. We need to wait that all sm finished work

PLAT-591: proper suite finalization

---

ledger-core/insolar/payload/marker_auth.go
ledger-core/virtual/authentication/service.go
ledger-core/virtual/authentication/service_test.go

Add support of messages which can come from any pulse

PLAT-575: skip check auth of some messages

---

ledger-core/virtual/authentication/service.go
ledger-core/virtual/authentication/service_test.go

Fix check of message with token: now sender can't be token approver 

Plat 596 fix check incomming messages

---

ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/integration/constructor_test.go

PLAT-590: additional checks in constructor tests

---

ledger-core/log/bpbuffer/buffer_slow_test.go

* reduced # of iterations and combinations

NOISSUE: Speedup slowtests for the backpressure buffer

---

ledger-core/application/testwalletapi/handlers.go
ledger-core/conveyor/conveyor.go
ledger-core/conveyor/conveyor_test.go
ledger-core/conveyor/main/conveyor_test_main.go
ledger-core/conveyor/sm_antique_test.go
ledger-core/insolar/dispatcher/dispatcher.go
ledger-core/instrumentation/inslogger/inslogger.go
ledger-core/virtual/handlers/handle_meta.go
ledger-core/virtual/integration/utils/loginterceptor.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/watermill_integration_test.go
ledger-core/virtual/statemachine/conveyor_dispatcher_test.go
ledger-core/virtual/statemachine/dispatcher.go
ledger-core/virtual/virtual.go

Tools allow check log event in test
Allow check log event in test
write code
How to use:
```
server, ctx := utils.NewUninitializedServer(nil, t)
defer server.Stop()
logHandler := func(arg interface{}) {
if err, ok := arg.(error); ok {
// test code here
}
}
logger := utils.InterceptLog(inslogger.FromContext(ctx), logHandler)
server.OverrideConveyorFactoryLogContext(inslogger.SetLogger(ctx, logger))
server.Init(ctx)
```

PLAT-604: log interceptor

---

ledger-core/virtual/integration/constructor_test.go

PLAT-508: add constructor call isolation test

---

ledger-core/virtual/integration/delegationtoken_test.go

Plat 567 test delegation token

---

ledger-core/testutils/debuglogger/update_chan.go

* fix mistake - a routine can leak when step debugger is stopped

NOISSUE: Fix accidental routine leak

---

ledger-core/virtual/integration/delegationtoken_test.go

Delegation token fail if wrong approver in token

PLAT-564: test check DT approver

---

ledger-core/network/hostnetwork/hostnetwork_test.go

if we start Stop procedure then error reply may fail to connect. We
should just check that reply with error.
use require.Fail in handler instead of strange solution
based on waitgroup

PLAT-592: not waiting for response may result in test failure

---

ledger-core/virtual/integration/delegationtoken_test.go

PLAT-565: test check DT approver != message sender

---

ledger-core/cmd/pulsewatcher/emoji.go
ledger-core/cmd/pulsewatcher/pulsewatcher.go
ledger-core/scripts/insolard/launchnet.sh

useful for big network setup
- pulsewatcher don't show emoji by defailt
- pulsewatcher **--emoji** flag
- launchnet.sh use **--emoji** flag to show emoji

NOISSUE: no emoji by default

---

ledger-core/virtual/integration/outgoing_test.go

- TestVirtual_CallContractOutgoingReturnsError  **C4971**

PLAT-392: outgoing call returns error to contract

---

.github/workflows/consensus-checks.yaml
.github/workflows/linux-checks.yaml

* Remove consensus checks from PRs
* Move generation and linter to a separate job

NOISSUE: speedup PR checks

---

ledger-core/virtual/integration/delegationtoken_test.go
ledger-core/virtual/integration/method_pulse_change_test.go

- added test with skip, because logic is not implemented
- updated testrail [case](https://insolar.testrail.io/index.php?/cases/view/5237&group_by=cases:section_id&group_order=asc&group_id=943) from 2 to 1

PLAT-612: method call when constructor execution is pending

---

ledger-core/network/messagesender/service.go

pulse in sendTarget is placed into message as "this is the current
pulse on sender and pulse of the message". It should be the current.
Doesn't matter if we use SendRole or SendTarget

PLAT-640: sendTarget should use the current pulse all the time

---

ledger-core/virtual/integration/method_test.go

NO_ISSUE_skip_bad_test

---

ledger-core/doc.go

PLAT-636: test changes

---

.github/bulldozer.yml
.github/policy.yml
ledger-core/doc.go

Installed to applications:
* Policy Bot: it allows us to extensively configure PR approval policies. Now it checks that PR is approved by one of the @insolar/dev-core team members.
* Bulldozer (bors replacement): this bot can merge and update PR branches automatically.
Bulldozer will squash and merge a PR when it has `ready to merge` label and all checks have passed. It will not merge if a PR has a `WIP` label.
Also, Bulldozer can auto-update PR branch if there are new commits in the base branch. Add an `autoupdate` label to the PR to enable this behavior.

PLAT-636: Palantir tools

---

ledger-core/virtual/integration/method_test.go

Test that method call fails without deduplication step if object is in the Missing state

PLAT-526: method will stop if obj state is Missing

---

ledger-core/virtual/integration/method_test.go

Add table test for past and current outgoing.Pulse

NOISSUE: method will stop if object state is Missing

---

ledger-core/virtual/integration/method_test.go
ledger-core/virtual/object/object.go
ledger-core/virtual/object/object.plantuml

Fixed all comments from https://docs.google.com/document/d/1LEGQZtAzt-Ii3JOiSlLWyiHR08UaMAjbxp1xmooyIa4/edit#

NOISSUE: Architectural supervision fixes

---

ledger-core/conveyor/smachine/perf/perf_test.go
ledger-core/conveyor/smachine/slot_machine_execute.go

* SlotMachine perf tests
* Minor perf fix

NOISSUE: Perf test for SlotMachine

---

ledger-core/virtual/integration/benchs/basic_test.go

NOISSUE: more benchmarks that involve our Test API

---

ledger-core/application/functest/api_test_utils.go
ledger-core/application/testwalletapi/README.md
ledger-core/application/testwalletapi/handlers.go
ledger-core/application/testwalletapi/testwalletserver.go
ledger-core/load/util/api_test_utils.go

Add API wallet/delete for tests

PLAT-412: add wallet/delete api

---

.github/workflows/master-checks.yaml
ledger-core/.gitignore

also added logs into ignored files

NOISSUE: fix path for extended logs in master checks

---

ledger-core/conveyor/conveyor.go
ledger-core/conveyor/conveyor_semaphore.go
ledger-core/conveyor/conveyor_semaphore_test.go
ledger-core/conveyor/smachine/smsync/sync_sema_partial.go
ledger-core/conveyor/smachine/smsync/sync_semaphore.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/virtual.go

Add hierarchical semaphore for limit runner parallelisms

PLAT-430: Add conveyor limiter to control max parallel processing

---

ledger-core/testutils/runner/logicless/service.go
ledger-core/virtual/integration/method_pulse_change_test.go

also fixed races in logicless runner service

PLAT-660: TestVirtual_Method_CheckPendingsCount hangs

---

ledger-core/virtual/integration/mock/publisher/checker/typed.go
ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher/template.go

Race was due to copying hdl (all struct, not pointer)

PLAT-663: checker.Typed race fix

---

.github/workflows/long-funcs.yaml
ledger-core/Makefile.testing
ledger-core/application/api/availability_test.go
ledger-core/log/bpbuffer/backpressure_buffer_test.go
ledger-core/network/integration/network_test.go

- introduced longtest tag for long runs
- excluded network/integration tests from long runs
- added long runs to workflows

PLAT-583: long integration runs

---

.github/mergeable.yml
.github/workflows/long-funcs.yaml
ledger-core/Makefile.testing
ledger-core/ledger/jet/prefix_tree_slow_test.go

Also, fix Mergeable rules so that assignee's review is required.

NOISSUE: add `prefix_tree_slow_test.go` tests to longtests   

---

.github/policy.yml

It has a very odd behavior with disapproval revoking

HOTFIX: remove disapproval rule

---

ledger-core/conveyor/conveyor_semaphore.go
ledger-core/conveyor/conveyor_semaphore_test.go
ledger-core/server/internal/virtual/components.go
ledger-core/virtual/execute/execute_semiintegration_test.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/handlers/vfindcallrequest_test.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/object/object.go
ledger-core/virtual/object/object_migration_test.go
ledger-core/virtual/object/object_publish_callsummary_test.go
ledger-core/virtual/object/object_test.go

Inherit SMObject semaphores from global limiter

PLAT-431: Inherit SMObject semaphores from global limiter

---

ledger-core/virtual/execute/execute_semiintegration_test.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/object/object.go
ledger-core/virtual/object/object_migration_test.go
ledger-core/virtual/object/object_publish_callsummary_test.go
ledger-core/virtual/object/object_test.go
ledger-core/virtual/tool/runnerlimiter.go
ledger-core/virtual/tool/runnerlimiter_test.go
ledger-core/virtual/virtual.go

Move runners limiter to virtual sub package

NOISSUE: move runner limiter to virtual/tool pkg

---

ledger-core/virtual/handlers/vfindcallrequest_test.go

PLAT-666: Fixed vfindcallrequest test

---

ledger-core/virtual/integration/contract_calls_test.go

i added assumption about VDelegatedRequesFinish.Count but forgot to wait it correctly

NOISSUE: fix retry test race

---

ledger-core/virtual/integration/method_test.go

updated case [C5106](https://insolar.testrail.io/index.php?/cases/view/5106)
case C4974 and test deleted  
case C5321 deleted(move logic to 5106)

PLAT-700: refactor tests 4974, 5106, 5321

---

ledger-core/conveyor/sm_pulse_slot.go
ledger-core/network/consensus/adapters/upstream.go

* move NSH stub so it can cover more cases
* to fix nil issue reported by perf testing

HOTFIX: fix improper NSH stub

---

ledger-core/network/gateway/base.go
ledger-core/network/gateway/bootstrap/requester.go
ledger-core/network/gateway/discovery_bootstrap.go
ledger-core/network/gateway/joiner_bootstrap.go
ledger-core/network/gateway/joiner_bootstrap_test.go
ledger-core/network/gateway/nonetwork.go
ledger-core/network/gateway/nonetwork_test.go

PLAT-653: revert use synckit.Backoff

---

ledger-core/Makefile.testing

NOISSUE: alternative testrail output hotfix (#563)

---

ledger-core/virtual/callregistry/working_table.go
ledger-core/virtual/callregistry/working_table_test.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/execute/execute_semiintegration_test.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/object/object.go
ledger-core/virtual/object/object_migration_test.go

1. remove pending counters 
2. use known table instead of 1.
3. update tests

PLAT-697: fix managing of pending counters

---

ledger-core/runner/adapter.go
ledger-core/testutils/runner/adapter/adapter.go
ledger-core/virtual/execute/execute.go

PLAT-649: simplification of PrepareExecutionAbort function

---

ledger-core/application/testutils/launchnet/launchnet.go
ledger-core/scripts/generate_insolar_configs.go
ledger-core/scripts/insolard/bootstrap_template.yaml
ledger-core/scripts/insolard/launchnet.sh

- clean up of launchnet.sh
- configurable nodes setup
- configurable nodes setup support in launchnet wrapper for func tests

NOISSUE: configurable, less hardcoded launchnet.sh

---

ledger-core/insolar/payload/validation_vcallresult.go
ledger-core/insolar/payload/validation_vfindcallresponse.go
ledger-core/virtual/integration/sender_test.go

also added stub for VCallResult

PLAT-686: implement VFindCallResponse validation

---

ledger-core/virtual/integration/deactivate_test.go

call deactivate with intolerable flag

PLAT-682: add test on deactivation with Intolerable flag

---

ledger-core/runner/requestresult/requestresult.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/integration/deactivate_test.go

Test: change pulse when half of the deactivation procedure is completed

PLAT-681: test object deactivation with change pulse

---

ledger-core/virtual/integration/delegationtoken_test.go

Fix naming in test and outgoing for DelegationToken

NOISSUE: fix naming in test and outgoing for DelegationToken 

---

ledger-core/virtual/integration/sender_test.go

TestVirtual_SenderCheck_With_ExpectedVE fixed, go test with 1000 and 5000 passed, go test with 10000 failed

PLAT-702: fix test TestVirtual_SenderCheck_With_ExpectedVE

---

ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/staterequest_test.go

NOISSUE: t.Log -> insrail.LogCase

---

ledger-core/insolar/payload/validation_vstatereport.go

Fix check UnorderedPendingCount for Inactive VStateReport

PLAT-717: fix check UnorderedPendingCount for Inactive VStateReport

---

ledger-core/application/functest/api_test_utils.go
ledger-core/application/testwalletapi/testwalletserver.go

NodeReadyMiddleware  returns 503 ServiceUnavailable until node is ready
It's not a bugfix, just for explicit error message

PLAT-699: NodeReadyMiddleware

---

ledger-core/virtual/integration/deactivate_test.go

add test for case https://insolar.testrail.io/index.php?/cases/view/5509

PLAT-709: test call after deactivation

---

ledger-core/virtual/execute/execute.go
ledger-core/virtual/integration/deduplication/constructor_test.go

Unskip test C5008: constructor deduplication on inactive state

PLAT-713: unskip test C5008: constructor deduplication on inactive state

---

ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/object/object.go

- make table test for object deactivation
- fix small bug in SMObject buildVStateReport step

PLAT-706: update happy-path test and fix small bug

---

ledger-core/appctl/affinity/affinity.go

use sha256 based target calculation instead of xor, to ensure proper objects distribution in network

NOISSUE: proper VirtualExecutorForObject

---

ledger-core/application/api/availability.go
ledger-core/application/api/availability_test.go

- one iteration of TestAvailabilityChecker_UpdateStatus was 5 sec
- test was rewritten to 5ms 
- build tags removed

PLAT-661: application/api tests timeout

---

ledger-core/virtual/integration/deactivate_test.go

Test finish partial object deactivation

PLAT-708: test finish partial object deactivation

---

ledger-core/virtual/integration/deactivate_test.go

case https://insolar.testrail.io/index.php?/cases/view/5507

PLAT-707: test deduplicate deactivation

---

ledger-core/virtual/integration/method_test.go

wait while all async calls will be executed

PLAT-721: wait for all AsyncCalls

---

ledger-core/insolar/contract/virtual.go
ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
ledger-core/insolar/payload/vcallflags.go
ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/deduplication/constructor_test.go
ledger-core/virtual/integration/deduplication_test.go
ledger-core/virtual/integration/method_pulse_change_test.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/vstatereport_test.go

PLAT-688: implement VDelegatedRequestFinshed validation

---

ledger-core/virtual/integration/method_test.go

add case Intollerable+Dirty in 5089 test
delete duplicates

PLAT-715: delete duplicate 5184 and 5123

---

ledger-core/virtual/integration/contract_calls_test.go

unskip test https://insolar.testrail.io/index.php?/cases/view/4959
delete case 5436

PLAT-703: delete duplicate 5436 and refactor 4959

---

ledger-core/virtual/integration/deduplication/constructor_test.go

delete case 5012 in testrail and in code
[task](https://insolar.atlassian.net/browse/PLAT-714)

PLAT-714: delete test 5012

---

ledger-core/insolar/payload/validate_vdelegatedcallresponse.go
ledger-core/insolar/payload/validation.go
ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/integration/constructor_test.go
ledger-core/virtual/integration/contract_calls_test.go
ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
ledger-core/virtual/integration/method_pulse_change_test.go
ledger-core/virtual/integration/outgoing_test.go
ledger-core/virtual/integration/sender_test.go
ledger-core/virtual/integration/vstatereport_test.go

PLAT-689: implentation of VDelegatedCallResponse checks

---

ledger-core/virtual/integration/method_test.go

Two Intolerable VCallRequests with Tolerable flags will be executed using Unordered semaphore.

PLAT-701: call two Intolerable methods with Tolerable flag

---

ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/method_test.go

NOISSUE: update tests

---

ledger-core/virtual/integration/vstatereport_test.go

delete 5239, because it is duplicate for 5237

NOISSUE: delete 5239

---

ledger-core/application/testwalletapi/handlers.go

switched to jsoniter serialization/deserialization in testwalletAPI

NOISSUE: use jsoniter in testwalletapi

---

ledger-core/virtual/integration/benchs/basic_test.go

NOISSUE: fix benchmark scenario

---

ledger-core/virtual/authentication/service.go
ledger-core/virtual/authentication/service_mock.go
ledger-core/virtual/authentication/service_test.go
ledger-core/virtual/handlers/handle_meta.go
ledger-core/virtual/integration/constructor_test.go
ledger-core/virtual/integration/delegationtoken_test.go

PLAT-498: IsMessageFromVirtualLegitimate -> CheckMessageFromAuthorizedVirtual

---

ledger-core/insolar/payload/validation.go

NOISSUE: fix bug with special base pulse

---

ledger-core/application/testwalletapi/statemachine/statemachine_test.go
ledger-core/insolar/payload/validation.go
ledger-core/insolar/payload/validation_vcallresult.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/integration/constructor_test.go
ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/deduplication/constructor_test.go
ledger-core/virtual/integration/deduplication_test.go
ledger-core/virtual/integration/method_test.go
ledger-core/virtual/integration/outgoing_test.go
ledger-core/virtual/integration/sender_test.go
ledger-core/virtual/integration/utils/vcallresult.go

Add logic checks of VCallResult

PLAT-685: add checks of VCallResult

---

ledger-core/virtual/integration/delegationtoken_test.go

one testrail id for table test

PLAT-730: tests refactoring

---

ledger-core/conveyor/conveyor.go
ledger-core/conveyor/conveyor_test.go
ledger-core/conveyor/conveyor_test.plantuml
ledger-core/conveyor/pulse_manager.go
ledger-core/conveyor/sm_pulse_slot.go
ledger-core/conveyor/sm_pulse_slot.plantuml
ledger-core/conveyor/smachine/slot.go
ledger-core/conveyor/smachine/slot_machine.go
ledger-core/conveyor/smachine/slot_machine_execute.go

* Stop cpu burning during "preparing pulse" phase
* Priority change for in-place slot updates

NOISSUE: better "preparing pulse" phase

---

ledger-core/conveyor/conveyor_test.go

PLAT-733: fix undercounting

---

ledger-core/log/logcommon/redirector.go
ledger-core/log/logcommon/redirector_test.go

* Do not print muted/filtered events to console in tests

NOISSUE: Mute filtered events

---

ledger-core/insolar/payload/delegationtokentype.go
ledger-core/insolar/payload/validation.go
ledger-core/insolar/payload/validation_vcallrequest.go
ledger-core/insolar/payload/validation_vcallresult.go
ledger-core/insolar/payload/validation_vdelegatedcallrequest.go
ledger-core/insolar/payload/validation_vdelegatedcallresponse.go
ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
ledger-core/insolar/payload/vcallrequestflags.go
ledger-core/network/messagesender/service.go
ledger-core/runner/execution/rpc.go
ledger-core/testutils/runner/logicless/service.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/integration/benchs/basic_test.go
ledger-core/virtual/integration/benchs/semi_test.go
ledger-core/virtual/integration/constructor_test.go
ledger-core/virtual/integration/contract_calls_test.go
ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/deduplication/constructor_test.go
ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
ledger-core/virtual/integration/deduplication_test.go
ledger-core/virtual/integration/delegationtoken_test.go
ledger-core/virtual/integration/method_pulse_change_test.go
ledger-core/virtual/integration/method_test.go
ledger-core/virtual/integration/object_test.go
ledger-core/virtual/integration/outgoing_test.go
ledger-core/virtual/integration/semaphore_test.go
ledger-core/virtual/integration/sender_test.go
ledger-core/virtual/integration/utils/vcallrequest.go
ledger-core/virtual/integration/vstatereport_test.go

PLAT-692: implement VCallRequest validation

---

ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/method_test.go

Tests refactoring: use WaitSignalsTimed for waiting VStateReport

PLAT-727: tests refactoring: simplify test

---

ledger-core/reference/global.go
ledger-core/virtual/execute/delegatedtokenrequest_test.go
ledger-core/virtual/execute/execute_isolation_negotiation_test.go
ledger-core/virtual/execute/execute_publish_callsummary_test.go
ledger-core/virtual/execute/execute_semiintegration_test.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/integration/deduplication/constructor_test.go
ledger-core/virtual/integration/deduplication_test.go
ledger-core/virtual/integration/delegationtoken_test.go

Check base's pulse number less or equal local's one

PLAT-589: additional check pulse number in NewRecordOf

---

ledger-core/insolar/payload/validation_vdelegatedcallrequest.go
ledger-core/insolar/payload/validation_vdelegatedcallresponse.go
ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
ledger-core/virtual/integration/deduplication/constructor_test.go
ledger-core/virtual/integration/utils/vcallrequest.go

Fix CallIncoming validation for Constructor cases

PLAT-736: callIncoming proper validation

---

ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go

move waits and change them to concrete waits

PLAT-664: rename vars and move waits

---

ledger-core/application/testwalletapi/statemachine/statemachine_test.go
ledger-core/insolar/payload/validation.go
ledger-core/insolar/payload/validation_vcallrequest.go
ledger-core/insolar/payload/validation_vcallresult.go
ledger-core/insolar/payload/validation_vdelegatedcallrequest.go
ledger-core/insolar/payload/validation_vdelegatedcallresponse.go
ledger-core/insolar/payload/validation_vdelegatedrequestfinished.go
ledger-core/insolar/payload/validation_vfindcallrequest.go
ledger-core/insolar/payload/validation_vfindcallresponse.go
ledger-core/insolar/payload/validation_vstatereport.go
ledger-core/insolar/payload/validation_vstaterequest.go
ledger-core/reference/global.go
ledger-core/virtual/execute/execute_isolation_negotiation_test.go
ledger-core/virtual/execute/execute_publish_callsummary_test.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/execute/migration_test.go
ledger-core/virtual/integration/constructor_test.go
ledger-core/virtual/integration/contract_calls_test.go
ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/sender_test.go
ledger-core/virtual/integration/utils/server.go

NOISSUE: refactor validation, code unification, more checks

---

ledger-core/runner/adapter.go
ledger-core/runner/execution/eventsink.go
ledger-core/runner/requestresult/outgoingresult.go
ledger-core/runner/runner.go
ledger-core/runner/runner_rpc.go
ledger-core/testutils/runner/logicless/service.go
ledger-core/virtual/execute/execute.go

- also rename Err -> Error
- closes PLAT-654

PLAT-365: make ExecutionContinue more sync

---

ledger-core/scripts/insolard/pulsar_template.yaml

Fix pulsar default configuration for launchnet

NOISSUE: fix pulsar default configuration for launchnet

---

ledger-core/virtual/memorycache/service.go
ledger-core/virtual/memorycache/service_mock.go

PLAT-773: change MemoryCache.Set method

---

ledger-core/virtual/object/info_test.go
ledger-core/virtual/object/object.go

* lines > 120 symbols
* refactor work with pulse
* added another test for TestInfo_GetEarliestPulse

NOISSUE: minor SMObject refactoring

---

ledger-core/insolar/payload/marker_auth.go
ledger-core/virtual/handlers/handle_meta.go
ledger-core/virtual/handlers/vcachedmemoryrequest.go
ledger-core/virtual/handlers/vcachedmemoryrequest.plantuml
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/vcachedmemoryrequest_test.go
ledger-core/virtual/memorycache/adapter/init.go
ledger-core/virtual/virtual.go

PLAT-751: add SMVCachedMemoryRequest

---

ledger-core/virtual/integration/vcachedmemoryrequest_test.go
ledger-core/virtual/memorycache/cache.go
ledger-core/virtual/memorycache/service.go

add simple memory cache: ctrlC/ctrlV of example cache

PLAT-772: simple memory cache

---

ledger-core/scripts/insolard/launchnet.sh

Don't generate  
1. migration addresses 
2. root member keys

NOISSUE: Don't generate unused files in launchnet.sh

---

ledger-core/conveyor/smachine/api_sync.go
ledger-core/conveyor/smachine/smsync/sync_ever.go
ledger-core/conveyor/smachine/smsync/sync_never.go

* a sync object that is always open

NOISSUE: ever open sync

---

ledger-core/conveyor/conveyor.go
ledger-core/conveyor/pulse_manager.go
ledger-core/conveyor/pulse_slot.go
ledger-core/conveyor/sm_pulse_slot.go
ledger-core/ledger/server/buildersvc/drop_assist_test.go
ledger-core/ledger/server/buildersvc/plash_assist.go
ledger-core/ledger/server/buildersvc/service.go
ledger-core/ledger/server/datawriter/smplash.go

* pass NSH from ledger to consensus

NOISSUE: nsh from ledger

---

ledger-core/testutils/journal/disp.go
ledger-core/testutils/journal/journal.go

* add tooling to ensure absence of events processed concurrently
* fix WaitAllAsyncCallsDone

NOISSUE: Fix journal for race

---

.github/codecov.yml
ledger-core/virtual/callregistry/request_table_test.go
ledger-core/virtual/callregistry/working_table_test.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
ledger-core/virtual/handlers/vdelegatedcallresponse_test.go
ledger-core/virtual/handlers/vdelegatedrequestfinished_test.go
ledger-core/virtual/handlers/vfindcallrequest_test.go
ledger-core/virtual/handlers/vstatereport_test.go
ledger-core/virtual/handlers/vstaterequest_test.go
ledger-core/virtual/integration/benchs/basic_test.go
ledger-core/virtual/integration/contract_calls_test.go
ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
ledger-core/virtual/integration/deduplication_test.go
ledger-core/virtual/integration/method_pulse_change_test.go
ledger-core/virtual/integration/method_test.go
ledger-core/virtual/integration/outgoing_test.go
ledger-core/virtual/integration/testwallet/pulse_change_test.go
ledger-core/virtual/integration/utils/vcallresult.go
ledger-core/virtual/object/info_test.go
ledger-core/virtual/object/object_migration_test.go
ledger-core/virtual/object/object_test.go
ledger-core/virtual/object/preservedstatereport/preservedstatereport_test.go

PLAT-784: refactor object reference in tests

---

ledger-core/instrumentation/insapp/init_components.go
ledger-core/instrumentation/insapp/pulse_manager.go
ledger-core/instrumentation/insapp/server_multi.go
ledger-core/network/servicenetwork/servicenetwork.go

NOISSUE: Isolate PulseManager

---

ledger-core/Makefile.testing

90m should be enough at the moment

NOISSUE: 30m is not enough for integration tests on GHA

---

ledger-core/ledger/server/buildersvc/bundle/api_writer.go
ledger-core/ledger/server/buildersvc/bundle/writeable_mock.go
ledger-core/ledger/server/buildersvc/bundle/writer_test.go

NOISSUE: Fix rollback test ordering

---

ledger-core/virtual/integration/constructor_test.go
ledger-core/virtual/integration/contract_calls_test.go
ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/deduplication_test.go
ledger-core/virtual/integration/method_pulse_change_test.go
ledger-core/virtual/integration/method_test.go
ledger-core/virtual/integration/outgoing_test.go

PLAT-787: refactor mock to outgoing

---

ledger-core/conveyor/smachine/slot.go
ledger-core/conveyor/smachine/slot_bargein.go
ledger-core/conveyor/smachine/slot_machine_execute.go
ledger-core/conveyor/smachine/slot_machine_migrate.go
ledger-core/instrumentation/convlog/logger.go

* a bit cleaner activity time tracking of Slot
* enables step stacking later

NOISSUE: improved time tracking

---

ledger-core/conveyor/conveyor.go
ledger-core/conveyor/sm_pulse_slot.go

* for for race when Present slot is created as new (had no Future status)

NOISSUE: PulseSlot race fix

---

ledger-core/rms/any.go
ledger-core/rms/registry.go
ledger-core/virtual/integration/mock/publisher/checker/typed.go
ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher/template.go

NOISSUE: enforce Any marshaling

---

.github/workflows/linux-checks.yaml
.github/workflows/master-checks.yaml
ledger-core/application/testutils/launchnet/cloud.go
ledger-core/cmd/insolard/cloud.go
ledger-core/configuration/apirunner.go
ledger-core/instrumentation/insapp/cloud_test.go

1. add GA for func test on cloud with race

PLAT-806: add ga actions

---

ledger-core/network/nds/uniproto/l2/uniserver/api_transport.go
ledger-core/network/nds/uniproto/l2/uniserver/server.go

* enable uniserver to use alternative transport implementations

NOISSUE: transport providers

---

ledger-core/virtual/handlers/vobjectvalidationreport.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/validation/validationreport_handling_test.go

PLAT-763: review fix

---

ledger-core/runner/requestresult/requestresult.go
ledger-core/runner/runner.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/integration/constructor_test.go
ledger-core/virtual/integration/contract_calls_test.go
ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/deduplication/constructor_test.go
ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
ledger-core/virtual/integration/memory_request_test.go
ledger-core/virtual/integration/outgoing_test.go

NOISSUE: parent concept doesn't work and don't know when we will add it back

---

ledger-core/runner/requestresult/requestresult.go
ledger-core/virtual/execute/execute.go

except in one place where it was used by mistake

NOISSUE: state id from RequestResult is not used anywhere

---

ledger-core/virtual/integration/benchs/basic_test.go

benchmark was broken on master checks

NOISSUE: fix benchmarks

---

.github/workflows/master-checks.yaml

we should store all logs from master checks

NOISSUE: store all logs from master checks

---

ledger-core/network/nds/msgdelivery/controller_massive_send_test.go
ledger-core/network/nds/msgdelivery/controller_test.go
ledger-core/network/nds/msgdelivery/uniproto_utils_test.go

NOISSUE: Create test utils methods for create multiple servers with connection to each other

---

ledger-core/rms/rms.go
ledger-core/rms/rmsbox/any.go

simplifies usage of the structure

NOISSUE: rms.NewAny function

---

ledger-core/network/nds/uniproto/api_packet_send.go
ledger-core/network/nds/uniproto/l2/uniserver/peer_transport.go

Fixed package size check limits

PLAT-837: Fixed package size check limits

---

ledger-core/application/functest/api_test_utils.go

NOISSUE: add traceid to error description in functests

---

ledger-core/conveyor/smachine/slot_machine_execute.go
ledger-core/conveyor/smachine/slot_machine_test.go

* migration delayed by replace was not applied after init

NOISSUE: migration delayed by replace was not applied after init

---

ledger-core/testutils/cloud/controller_test.go

NOISSUE: TestController_PartialDistribute: fix logging

---

ledger-core/network/nds/msgdelivery/ctl_dedup.go
ledger-core/network/nds/msgdelivery/ctl_retry_state_worker.go

PLAT-843: Fixed message delivery (benchmark hangs)

---

ledger-core/conveyor/smachine/api_context.go
ledger-core/conveyor/smachine/context_async.go
ledger-core/conveyor/smachine/context_basic.go
ledger-core/conveyor/smachine/context_misc.go
ledger-core/conveyor/smachine/slot_bargein.go
ledger-core/conveyor/smachine/slot_error.go
ledger-core/conveyor/smachine/slot_machine_migrate.go
ledger-core/conveyor/smachine/slot_subroutine.go
ledger-core/conveyor/smachine/state_update_type.go

* AffectedStep will return zero value when is called in a handler of a parent while subroutine SM is active
* Jump/JumpExt will fail fast on zero/nil step

NOISSUE: Protection of AffectedStep

---

ledger-core/application/benchs/cloud_test.go
ledger-core/application/benchs/fullnetwork_test.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/handlers/vstatereport_test.go
ledger-core/virtual/integration/benchs/basic_test.go
ledger-core/virtual/integration/benchs/semi_test.go

fixed benchmarks that always fail and tests that sporadically failed

NOISSUE: fix benchmarks that stopped working after register

---

ledger-core/application/api/availability.go
ledger-core/instrumentation/insapp/init_components.go
ledger-core/scripts/insolard/launchnet.sh
ledger-core/virtual/execute/execute_test.go

It caused sporadic failures and isn't needed, for now

NOISSUE: disable keeperd in functests

---

ledger-core/rms/proto_vnvn.pb.go
ledger-core/rms/proto_vnvn.proto
ledger-core/rms/proto_vnvn_validation_vobjecttranscriptreport.go

update proto; add validate for VObjectTranscriptReport

NOISSUE: new msg validations

---

ledger-core/cmd/protoc-gen-ins/plugins/gogobased/unmarshal.go
ledger-core/rms/proto_catalog.pb.go
ledger-core/rms/proto_common.pb.go
ledger-core/rms/proto_legacy.pb.go
ledger-core/rms/proto_legacy_packet.pb.go
ledger-core/rms/proto_legacy_profile.pb.go
ledger-core/rms/proto_records.pb.go
ledger-core/rms/proto_vnlmn.pb.go
ledger-core/rms/proto_vnvn.pb.go
ledger-core/rms/rmsbox/any_record_lazy.go
ledger-core/rms/rmsbox/any_record_lazy_body.pb.go
ledger-core/rms/rmsreg/registry.go
ledger-core/rms/rmsreg/serializable.go

* provide last successful position from UnmarshalWithUnknownCallback

NOISSUE: improve UnmarshalWithUnknownCallback

---

ledger-core/reference/decoder_test.go
ledger-core/reference/local.go
ledger-core/virtual/integration/utils/server.go

NOISSUE: Remove deprecated GetHash

---

ledger-core/virtual/object/object_test.go

NOISSUE: delay test fails

---

ledger-core/application/testutils/launchnet/cloud.go

use manual pulsar when it is configured as manual

NOISSUE: fix benchmarks with manual pulsar

---

.github/workflows/consensus-checks.yaml

Update reporter version to `v1.0.5`. Some report style fixes introduced.

PLAT-257: update reporter version

---

ledger-core/network/nds/msgdelivery/controller_bench_test.go
ledger-core/network/nds/msgdelivery/controller_parallelism_test.go
ledger-core/network/nds/msgdelivery/protocol_test.go
ledger-core/network/nds/msgdelivery/uniproto_utils_test.go
ledger-core/network/nds/uniproto/l2/uniserver/server.go

PLAT-827: Implement parallelism test

---

ledger-core/virtual/integration/benchs/basic_test.go

NOISSUE: fix benches that were broken by changes in object descriptor

---

ledger-core/virtual/execute/execute.go
ledger-core/virtual/handlers/vcachedmemoryrequest.go
ledger-core/virtual/handlers/vstatereport_test.go
ledger-core/virtual/integration/deactivate_test.go
ledger-core/virtual/integration/deduplication/constructor_test.go
ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
ledger-core/virtual/integration/deduplication_test.go
ledger-core/virtual/integration/memory_request_test.go
ledger-core/virtual/integration/method_pulse_change_test.go
ledger-core/virtual/integration/method_test.go
ledger-core/virtual/integration/statereport_test.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/utils/vstatereport.go
ledger-core/virtual/integration/vdelegated_test.go
ledger-core/virtual/integration/vstatereport_test.go
ledger-core/virtual/object/object.go
ledger-core/virtual/object/preservedstatereport/preservedstatereport_test.go

NOISSUE: Reference field in rms.ObjectState should global ref

---

ledger-core/virtual/integration/benchs/basic_test.go

HOTFIX: fix broken BenchmarkTestAPIGetBalance

---

ledger-core/runner/bench_test.go

HOTFIX: another broken benchmark

---

ledger-core/virtual/integration/mock/referencebuilder/checker/typed.go
ledger-core/virtual/integration/mock/referencebuilder/cmd/insolar-mockgenerator-referencebuilder/template.go

todo: https://insolar.atlassian.net/browse/PLAT-856

NOISSUE: fix type conversion

---

ledger-core/virtual/integration/mock/referencebuilder/cmd/insolar-mockgenerator-referencebuilder/main.go

NOISSUE: filter records in referencebuilder mock generator

---

.github/workflows/linux-checks.yaml
ledger-core/Makefile.testing

* benchmarks run with 1 iteration

NOISSUE: added benchmark checks on PR

---

ledger-core/virtual/execute/execute.go
ledger-core/virtual/execute/execute.plantuml
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/lmn/register.go
ledger-core/virtual/lmn/register_context.go
ledger-core/virtual/lmn/register_send.go
ledger-core/virtual/lmn/register_waitsafe.go
ledger-core/virtual/lmn/saferesponsecounter.go

PLAT-849: isolate registration context

---

.github/workflows/consensus-checks.yaml

NOISSUE: stop scheduled consensus checks

---

.github/workflows/sonar.yml

Add workflow running sonar-scanner.

OPS-182: add sonar workflow

---

ledger-core/application/testwalletapi/statemachine/statemachine.go
ledger-core/application/testwalletapi/statemachine/statemachine_test.go
ledger-core/rms/rmsbox/provider_ref.go
ledger-core/server/internal/virtual/app_factory.go
ledger-core/virtual/execute/delegatedtokenrequest_test.go
ledger-core/virtual/execute/execute.go
ledger-core/virtual/execute/execute_semiintegration_test.go
ledger-core/virtual/execute/execute_test.go
ledger-core/virtual/execute/migration_test.go
ledger-core/virtual/integration/utils/server.go
ledger-core/virtual/integration/utils/vcallrequest.go
ledger-core/virtual/testutils/utils.go
ledger-core/virtual/testutils/virtualdebugger/stepmachine.go
ledger-core/virtual/virtual.go
ledger-core/virtual/vnlmn/register.go
ledger-core/virtual/vnlmn/register_context.go
ledger-core/virtual/vnlmn/register_send.go
ledger-core/virtual/vnlmn/register_waitsafe.go

later we can integrate that machanism into reference builder, if needed

PLAT-629: replace reference builder with rms lazy references

---

.github/workflows/long-integration.yaml
.github/workflows/master-checks.yaml
.github/workflows/windows-checks.yaml

Disable scheduled test runs to stop alerts in #notify-platform

NOISSUE: disable cron tests
