insolar/assured-ledger

- ledger-core/v2/Makefile
- ledger-core/v2/go.mod
- ledger-core/v2/network/consensus/gcpv2/api/transport/full_introduction_reader_mock.go
- ledger-core/v2/network/consensus/gcpv2/api/transport/packet_readers.go
Minimock generated on `transport.FullIntroductionReader`
for some reason adds weird cyclic imports.
I've added `goimports` run after minimock generation to fix this.
Goimports fails if runs with '-mod=vendor' go flag. So I had to
Add GOFLAGS="" in `generate` target in Makefile.
> HOTFIX: fix bad imports in minimock

- ledger-core/v2/Makefile.testing
skipped ledger-v2 directory from unit and integration tests run
> NOISSUE: skip ledger-v2 directory from test runs

- .github/workflows/tag_processing.yaml
Add env:JIRA_LOGIN to git-tag-handler job
> OPS-134: add jira_login to git-tag-handler job

- ledger-core/v2/.golangci.yml
increase golangci timeout because of big code base it exceeds default 1m
> NOISSUE: increase golangci timeout

- .github/workflows/common.yaml
Because all unit test are run in slowtest step
> NOISSUE: remove unit tests step

- ledger-core/v2/conveyor/smachine/api_context.go
- ledger-core/v2/conveyor/smachine/context_share_publish.go
add method to InOrderStepContext interface and implementation in SlotContext. Implementation in SlotContext just to comply with the interface, not sure if it's required in this context or not.
> PLAT-226: GetPublishedGlobalAliasAndBargeIn method on context

- .github/workflows/common.yaml
All checks like linter, clean working dir and tests are run even if the previous step fails. This allows us to see more potential bugs in one CI run.
> NOISSUE: run tests even if previous step fails

- ledger-core/v2/application/cmd/main/main.go
- ledger-core/v2/application/testutils/launchnet/launchnet.go
- ledger-core/v2/cmd/pulsard/main.go
- ledger-core/v2/configuration/hostnetwork.go
- ledger-core/v2/go.mod
- ledger-core/v2/network/options.go
- ledger-core/v2/scripts/generate_insolar_configs.go
- ledger-core/v2/scripts/insolard/launchnet.sh
…luanch pulsar with option --one-shot. 3. Increase PulseWatchdogTimeout up to 1 month
1. Func tests run luanchnet.sh without pulsar. 
2. Func tests run pulsar with option --one-shot. 
3. Increase PulseWatchdogTimeout up to 1 month to prevent crash of nodes
> PLAT-238: Don't change pulse in insolar net

- ledger-core/v2/Makefile
- ledger-core/v2/vanilla/reflectkit/reflect_accessor.go
- ledger-core/v2/vanilla/unsafekit/byte_string_test.go
Since go 1.14 `checkptr` check is enabled if `-race` flag is present.
It checks the following:
1. When converting unsafe.Pointer to *T, the resulting pointer must be aligned appropriately for T.
2. If the result of pointer arithmetic points into a Go heap object, one of the unsafe.Pointer-typed operands must point into the same object.
See go release notes for details: https://golang.org/doc/go1.14#compiler
I've failed to fix TestRetentionByByteString properly so after discussion with @cyraxred we decided to skip this check in this test function.
> PLAT-292: fix some problems with data race and `checkptr`

- ledger-core/v2/conveyor/sm_pulse_slot.go
- ledger-core/v2/conveyor/smachine/slot.go
- ledger-core/v2/conveyor/smachine/slot_machine.go
- ledger-core/v2/conveyor/smachine/slot_machine_execute.go
- ledger-core/v2/conveyor/smachine/slot_utils.go
- ledger-core/v2/virtual/execute/execute.go
- fix for short-loop messing up AcquireForThisStep, added check for sync dependencies after each short-loop
- added exclusion for non-migrate states for short-loop
- fixed unnecessary looping behavior in conveyor
> PLAT-321 short looping fixes

- ledger-core/v2/application/testwalletapi/handlers.go
- ledger-core/v2/application/testwalletapi/statemachine/handler.go
- ledger-core/v2/application/testwalletapi/statemachine/statemachine.go
- ledger-core/v2/conveyor/conveyor.go
- ledger-core/v2/virtual/integration/statereport_test.go
- ledger-core/v2/virtual/integration/staterequest_test.go
- ledger-core/v2/virtual/integration/stateunavailable_test.go
- ledger-core/v2/virtual/integration/utils/server.go
- ledger-core/v2/virtual/virtual.go
1. switched to AddInputExt in testWalletAPI for guranteed behaviour of testAPI responses
2. moved to context propagation for logging purposes.
> PLAT-287: Move to AddInputExt

- ledger-core/v2/conveyor/smachine/api_context.go
- ledger-core/v2/conveyor/smachine/context_basic.go
- ledger-core/v2/conveyor/smachine/example/main/main.go
- ledger-core/v2/conveyor/smachine/example/run.go
- ledger-core/v2/conveyor/smachine/example/run_test.go
- ledger-core/v2/conveyor/smachine/execution_context_mock.go
- ledger-core/v2/conveyor/smachine/slot_machine.go
- ledger-core/v2/conveyor/smachine/slot_machine_execute.go
* Added a version of InitChild with an explicit post-init callback which provides safe access to both SMs after the child SM is initialized
> NOISSUE-explicit-post-init

- ledger-core/v2/network/hostnetwork/hostnetwork_test.go
TestNewHostNetwork seems to be fixed on Windows. CI checks were executed twice, all OK.
>  PLAT-334: TestNewHostNetwork seems to be fixed on Windows 

- ledger-core/v2/network/hostnetwork/hostnetwork_test.go
Reverts insolar/assured-ledger#160
> Revert " PLAT-334: TestNewHostNetwork seems to be fixed on Windows "

- ledger-core/v2/network/hostnetwork/hostnetwork_test.go
fix for TestNewHostNetwork race on sending replies, causing the test to fail randomly
> PLAT-334: fix race in TestNewHostNetwork

- ledger-core/v2/scripts/insolard/launchnet.sh
Fix running test_func when project root folder not in GOPATH
Fix check root folder in launchnet.sh
run `make test_func`
> NOISSUE: fix run launchnet.sh outside from GOPATH

- ledger-core/v2/virtual/execute/execute.go
- ledger-core/v2/virtual/execute/execute_test.go
- ledger-core/v2/virtual/handlers/vstatereport.go
- ledger-core/v2/virtual/object/catalog.go
- ledger-core/v2/virtual/object/catalog_mock.go
- ledger-core/v2/virtual/object/object.go
- ledger-core/v2/virtual/object/object_migration_test.go
there is no need in reason, SM object shares data, goes further into
sending VStateRequest, constructor or VStateReport just fill in data
immediately before request is sent
> PLAT-316: create SM object without reason

- ledger-core/v2/instrumentation/inslogger/consprint/console_printer.go
* fix for occasional incomparable error when console printer is active
> NOISSUE: Logger may fail due to incomparable error when console printer is active

- ledger-core/v2/application/builtin/contract/testwallet/testwallet.wrapper.go
- ledger-core/v2/insolar/contract/virtual.go
- ledger-core/v2/insolar/payload/vcallrequestflags.go
- ledger-core/v2/insolar/payload/vcallrequestflags_test.go
- ledger-core/v2/virtual/execute/execute.go
- ledger-core/v2/virtual/execute/execute_isolation_negotiation_test.go
removed methodIsolation from heap
- Reserved 0 value for flags, as discussed with @cyraxred 
- Added IsZero for flags and for contract.MethodIsolation struct
- Check methodIsolation fillin with IsZero
run tests
> PLAT-329: remove methodIsolation from heap

- ledger-core/v2/Makefile.testing
- ledger-core/v2/application/testutils/launchnet/launchnet.go
- ledger-core/v2/cmd/pulsard/main.go
- ledger-core/v2/scripts/insolard/launchnet.sh
New Makefile target for run test_func many times with active pulse
* Allow to pulsard read run mode and pulse time from os ENV
* Add to Makefile.testing target for run with params `FUNCTEST_COUNT=100 PULSAR_ONESHOT=FALSE PULSAR_PULSETIME=3000`
Run `make test_func_slow`
Add to pulsard ENV settings
* `PULSAR_ONESHOT` - if it have one of values `1`, `True`, `T`, `t`, `TRUE` pulsar will send one pulse to network and stop. Command line parameter `-o` set this mode too
* `PULSAR_PULSETIME` - allow override configuration file settings and set pulse time
> PLAT-351: activate pulse changing in network

- ledger-core/v2/virtual/execute/execute_test.go
- ledger-core/v2/virtual/handlers/vstatereport.go
- ledger-core/v2/virtual/handlers/vstatereport_test.go
- ledger-core/v2/virtual/handlers/vstaterequest.go
- ledger-core/v2/virtual/handlers/vstaterequest_test.go
- ledger-core/v2/virtual/integration/staterequest_test.go
- ledger-core/v2/virtual/object/catalogwrapper_mock.go
- ledger-core/v2/virtual/object/object.go
- ledger-core/v2/virtual/object/object_migration_test.go
- ledger-core/v2/virtual/testutils/shareddata/utils.go
* Fix sending VStateReport without Descriptor in SMObject
* Fix processing VStateReport without LatestDirtyState
SMObject send VStateReport with nil in LatestDirtyState. VStateReport handler create SMObject with state Empty
Run test 
> PLAT-379: Fix send and processing VStateReport without SMObject.descriptor

- .github/workflows/linux-checks.yaml
- ledger-core/v2/Makefile.testing
The proposed patch already catches some issues. I believe this is good enough for now.
> PLAT-352: run functest many times on `master` with reduced pulse time

- ledger-core/v2/virtual/handlers/vstatereport.go
- ledger-core/v2/virtual/object/object.go
VStateReport handler should store EarliestRequestPulse in state object
Fillage of EarliestRequestPulse in different PR
> PLAT-311: process VStateReport fields for earliest pulses

- ledger-core/go.mod
- ledger-core/runner/adapter.go
- ledger-core/runner/runner.go
- ledger-core/testutils/runner/adapter/adapter.go
- ledger-core/testutils/runner/logicless/execution.go
- ledger-core/testutils/runner/logicless/service.go
- ledger-core/virtual/execute/execute.go
- ledger-core/virtual/integration/mock/defaultchecker.go
- ledger-core/virtual/integration/mock/publisher.go
- ledger-core/virtual/integration/mock/typepublishchecker.go
- ledger-core/virtual/integration/utils/helper.go
- ledger-core/virtual/integration/utils/server.go
- ledger-core/virtual/integration/utils/wallet.go
- ledger-core/virtual/statemachine/logger_step.go
- ledger-core/virtual/testutils/slotdebugger/stepmachine.go
- ledger-core/virtual/virtual.go
* also implement simplier publisher checker
Example of test with both features:
``` go
// Copyright 2020 Insolar Network Ltd.
// All rights reserved.
// This material is licensed under the Insolar License version 1.0,
// available at https://github.com/insolar/assured-ledger/blob/master/LICENSE.md.
package integration
import (
"testing"
"time"
"github.com/gojuno/minimock"
"github.com/insolar/assured-ledger/ledger-core/insolar"
"github.com/insolar/assured-ledger/ledger-core/insolar/contract"
"github.com/insolar/assured-ledger/ledger-core/insolar/payload"
"github.com/insolar/assured-ledger/ledger-core/reference"
"github.com/insolar/assured-ledger/ledger-core/runner/execution"
"github.com/insolar/assured-ledger/ledger-core/runner/executionevent" …
```
> PLAT-420: Implement runner adapter mock

- README.md
linux-checks are not executed on master any longer, there are master-checks instead.
> NOISSUE: fix badges in README.md

- ledger-core/virtual/object/request_table.go
- ledger-core/virtual/object/request_table_test.go
Fix RequestTable.GetList return pointer to copy of RequestList
RequestTable will save pointers to RequestList and  return it in GetList
> NOISSUE: fix RequestTable.GetList return pointer to copy of RequestList

- ledger-core/Makefile.testing
kill + pgrep returns error on Linux if insolard is not running
> NOISSUE: fix pgrep+kill workaround for Linux

- ledger-core/insolar/jet/affinity.go
- ledger-core/network/messagesender/service.go
- ledger-core/virtual/handlers/vcallrequest.go
- fix for vcallrequest that goes to antique slot (replacing SM had no dependencies)
- some more throw usage instead of errors in messagesender
- removed wrapf from jet affinityHelper
> NOISSUE: fix for vcallrequest that goes to antique slot

- ledger-core/application/testwalletapi/statemachine/statemachine.go
- ledger-core/virtual/execute/execute.go
- ledger-core/virtual/execute/execute.plantuml
- ledger-core/virtual/execute/execute_test.go
- ledger-core/virtual/execute/migration_test.go
- ledger-core/virtual/handlers/vdelegatedcallrequest.go
fixed some execution errors:
- proper deduplication for requests that comes from previous pulses
- proper object descriptor class getter
- leaking migration
> NOISSUE: execute fixes: deduplication, migration leak, wrong descriptor

- ledger-core/conveyor/smachine/api_logger.go
- ledger-core/conveyor/smachine/context_call.go
- ledger-core/conveyor/smachine/exec_adapter_call.go
- ledger-core/conveyor/smachine/exec_adapter_callback.go
- ledger-core/testutils/slotdebugger/smhelper.go
* added expired-cancel and expired-result statuses
> NOISSUE: Enable logging for expired async callbacks

- ledger-core/virtual/execute/delegatedtokenrequest.go
early return from sub-SM without response, calling SM (SM Execute)
panics and stops execution
> PLAT-480: missing return could result in illegal state

- ledger-core/application/testwalletapi/statemachine/statemachine.go
- ledger-core/virtual/execute/delegatedtokenrequest.go
- ledger-core/virtual/execute/execute.go
writing into registering SM's fields from outside of smachine.BargeInCallbackFunc
is not safe
> PLAT-490: BargeInCallbackFunc is synchronized with registering SM

- ledger-core/virtual/execute/delegatedtokenrequest.go
- ledger-core/virtual/handlers/vdelegatedcallrequest.go
- ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
- ledger-core/virtual/handlers/vdelegatedrequestfinished.go
- ledger-core/virtual/handlers/vdelegatedrequestfinished_test.go
- ledger-core/virtual/handlers/vstatereport.go
- ledger-core/virtual/handlers/vstatereport_test.go
- ledger-core/virtual/object/object.go
- ledger-core/virtual/object/object_migration_test.go
- ledger-core/virtual/object/object_test.go
- ledger-core/virtual/object/request_table.go
- ledger-core/virtual/object/request_table_test.go
Send VStateReport with pending counters witch was registered as delegated and does not finished yet. This values stored in PendingTable. Active(Un|O)rderedPendingCount was renamed to PreviousExecutor(Un|O)rderedPendingCount and used as constant
Check values of counters with values of active counters in table of pending execution. Logging warning if values mismatched and correct it.
Run test. Addition test case will be in PLAT-471
> PLAT-479: Send correct pending counters in VStateReport when pulse changed

- ledger-core/conveyor/conveyor.go
- ledger-core/conveyor/conveyor_test.go
- ledger-core/conveyor/pulse_data_holder.go
- ledger-core/pulse/pulse_data.go
- ledger-core/pulse/pulse_range.go
- ledger-core/virtual/handlers/handle_meta.go
- ledger-core/virtual/virtual.go
* enable to use pulse.Range for expected (future) pulse data
* look up for pulse.Range in conveyor's cache
* additional checks for missing pulse.Range (event is too old)
> PLAT-557 Provide pulse.Range for in-cache antique slots.

- ledger-core/runner/runner.go
- ledger-core/virtual/execute/execute.go
- ledger-core/virtual/integration/constructor_test.go
- ledger-core/virtual/integration/utils/server.go
Added error instead of panic when failed to find contract descriptor.
Added test checking that constructor calls with empty or random class ref return an error.
> PLAT-394, PLAT-507: constructor call with bad class ref returns an error

- ledger-core/virtual/execute/execute.go
- ledger-core/virtual/execute/execute.plantuml
- ledger-core/virtual/integration/method_test.go
- update C4976 TestVirtual_BadMethod_WithExecutor
- provide VCallResult with a wrapped error instead of panic
> PLAT-397: bad contract method call returns error instead of panic

- ledger-core/virtual/handlers/vstaterequest.go
- ledger-core/virtual/object/finalizedstate/storage.go
- ledger-core/virtual/object/object.go
- ledger-core/virtual/object/object.plantuml
- ledger-core/virtual/object/object_migration_test.go
-  Move SMStateFinalizer to separate step 
-  rename migrate to stepMigrate 
-  remove pulse number from ReportKey
> PLAT-577: Move SMStateFinalizer to separate step 

- ledger-core/virtual/execute/execute_test.go
New test for check that message VStateReport will be send with state Missing if constructor was interrupted before runner call
Add test
Run test
> PLAT-505: Test: Send VStateReport with Missing state if constructor was interrupted before runner call

- ledger-core/virtual/execute/execute.go
- ledger-core/virtual/execute/execute_test.go
- ledger-core/virtual/object/object.go
- ledger-core/virtual/object/working_table.go
- ledger-core/virtual/object/working_table_test.go
Split request/result in working_table.go, now result stored in a separate map[reference.Global]Summary
working_table_test.go modified
https://insolar.atlassian.net/browse/PLAT-580
> PLAT-580: Split request/result in working_table.go

- ledger-core/virtual/execute/execute_test.go
- ledger-core/virtual/object/info_test.go
- ledger-core/virtual/object/request_table.go
- ledger-core/virtual/object/request_table_test.go
- ledger-core/virtual/object/working_table.go
- ledger-core/virtual/object/working_table_test.go
- sync tables behaviour
- hide list method that should not be called outside of table
- added bench for memory usage
before
```
pkg: github.com/insolar/assured-ledger/ledger-core/virtual/object
BenchmarkPendingTable-12    	 3951997	       285 ns/op	     304 B/op	       6 allocs/op
BenchmarkWorkingTable-12    	 4537809	       244 ns/op	     240 B/op	       6 allocs/op
```
after
```
goos: darwin
goarch: amd64
pkg: github.com/insolar/assured-ledger/ledger-core/virtual/object
BenchmarkPendingTable-12    	 7344967	       154 ns/op	     160 B/op	       4 allocs/op
BenchmarkWorkingTable-12    	 5528679	       192 ns/op	     208 B/op	       5 allocs/op
```
> NOISSUE: sync pending table realization with working table

- ledger-core/virtual/handlers/vdelegatedcallrequest_test.go
- ledger-core/virtual/integration/contract_calls_test.go
- ledger-core/virtual/integration/delegated_finished_test.go
- ledger-core/virtual/integration/method_test.go
- ledger-core/virtual/integration/vdelegated_test.go
- fix syntax t.Skip for valid integation testrail with jira
- refactor tests to table
- add test for call unordered B from unordered A
- refactor cases in testrail https://insolar.testrail.io/index.php?/suites/view/78&group_by=cases:section_id&group_order=asc
- move happy-path tests in contract_calls_test.go
> PLAT-555: refactor method tests and added one case 

- ledger-core/testutils/mocklog/wrap_t.go
- ledger-core/vanilla/args/var_agrs.go
* mocklog.T(t) that usable for minimocks to report full stacktrace on errors/fatals
> NOISSUE: Helper for minimock to report full stacktrace

- ledger-core/virtual/integration/vdelegated_test.go
```
$ go test ./virtual/integration/ -tags "convlogtxt" -test.run ^TestVirtual_VDelegatedCallRequest_GetBalance$ -race -count=1000
ok  	github.com/insolar/assured-ledger/ledger-core/virtual/integration	21.296s
$ go test ./virtual/integration/ -tags "convlogtxt" -test.run ^TestVirtual_VDelegatedCallRequest_GetBalance$ -count=1000
ok  	github.com/insolar/assured-ledger/ledger-core/virtual/integration	3.563s
```
> PLAT-449: unskip and update test

- ledger-core/network/servicenetwork/servicenetwork.go
commented graceful stop logic. it is broken and we need to fix it in R1 with new network part
Run make test_func, make sure that no insolard nodes left working
> PLAT-578: disable graceful stop for network. Will fix it later on

- ledger-core/application/testwalletapi/handlers.go
- ledger-core/application/testwalletapi/statemachine/statemachine.go
- ledger-core/application/testwalletapi/statemachine/statemachine.plantuml
- ledger-core/application/testwalletapi/statemachine/statemachine_test.go
* limit number of retries
* object was not calculated correctly constructors
* idea of unpublishing bargein was not working, pulse was the same all
the time, just placed first send into one step and resend into
another
* set migration after first send
* write tests
> PLAT-553: retries limit in SMTestAPICall and fixes

- ledger-core/virtual/execute/execute.go
- ledger-core/virtual/integration/constructor_test.go
requests on objects that don't exist or don't yet exist cause
StateReport to be send with Missing state. Such StateReport is caused by
constructor that hit SMExecute, but didn't reach execution before pulse
change. Constructor is retried in the new pulse and is excuted on
Missing state.
> PLAT-641: constructor can run on missing state, update correctly

- ledger-core/virtual/integration/constructor_test.go
- ledger-core/virtual/integration/statereport_test.go
* delete one test C4835 that is complete duplication of C4995
* in all happy paths switch pulse and check state report that we send
afterwards
* some tiny renaming
* TestRail updated accordingly
> improve happy path tests of constructors

- ledger-core/log/builder.go
if we don't re-use then every call to inslogger.Clean creates a new
output with BackPressureBuffer that has a goroutine that stays forever
and is quite heavy.
> PLAT-644: even if we can not copy logger, we can re-use output

- ledger-core/virtual/object/catalog.go
- ledger-core/virtual/object/object.go
- ledger-core/virtual/object/object_migration_test.go
- ledger-core/virtual/object/object_publish_callsummary_test.go
- ledger-core/virtual/object/object_test.go
Stringification of reference is way to slow for such purpose
In theory we can wrap reference into special struct, but in this case
I think that this is object's primary data and it's ok to use object's
reference directly.
> NOISSUE: use object reference as publishing key for object's shared data

- ledger-core/virtual/integration/benchs/basic_test.go
- ledger-core/virtual/integration/utils/server.go
- ledger-core/virtual/testutils/utils.go
benchmark includes VCallRequest processing without message
deserialization and with executor and contract code.
time between VCallRequest and VCallResult messages is timed.
Finalization of one request slightly overlaps with start of a new one.
> NOISSUE: benchmark GetBalance on TestWallet contract

- ledger-core/virtual/integration/mock/typepublishchecker.go
- ledger-core/virtual/integration/outgoing_test.go
also added BeforeCount for every TypedChecker mock
Problem with test was that `IncrementPulseAndWaitIdle` wasn't giving a chance for `firstVCallRequest = false` sometimes.
Fixed with new `CountBefore()` in TypePublishChecker mock
> PLAT-638: and PLAT-646 fix flacky tests

- ledger-core/application/api/availability_test.go
- ledger-core/application/api/seed_test.go
- ledger-core/network/hostnetwork/hostnetwork_test.go
- ledger-core/network/integration/suite_test.go
- ledger-core/network/servicenetwork/servicenetwork_test.go
- ledger-core/server/internal/headless/components_test.go
- ledger-core/server/internal/virtual/components_test.go
- ledger-core/virtual/integration/delegated_finished_test.go
The only place that still holds IgnoreError are network integration tests, which would be reworked
> PLAT-367: get rid of IgnoreAllErrors from most of the tests

- ledger-core/application/testwalletapi/handlers.go
error contains all information:
```
$ curl -d '{ "walletRef": "insolar:1AuUjAIOV-8J7qVVi_a3FE" }'  "127.0.0.1:32304/wallet/delete" | jq
{
"traceID": "a54a1928d58a75401447a13c105a7a9b",
"error": "Failed to create reference from string;\tinvalid reference: ref=1AuUjAIOV-8J7qVVi_a3FE err=illegal base64 data at input byte 20"
}
$ curl -d '{ "walletRef": "insolar:1AuUjAIOV-8J7qVVi_a3FE" }'  "127.0.0.1:32304/wallet/get_balance" | jq
{
"amount": 1000,
"traceID": "f549b613f5ee88de6168a531220a56a9",
"error": "Failed to create reference from string;\tinvalid reference: ref=1AuUjAIOV-8J7qVVi_a3FE err=illegal base64 data at input byte 20"
}
```
> NOISSUE: remove unnecessary Sprintf

- .github/bulldozer.yml
Despite `options.squash.body` param is set to "empty_body" bulldozer (or GitHub) sets the summary of all commits in a commit message body.
I've replaced "empty_body" with "pull_request_body" as it is the lesser of two evils.
> NOISSUE: PR body in squash commit message

- ledger-core/virtual/handlers/vfindcallrequest.go
- ledger-core/virtual/handlers/vfindcallrequest.plantuml
- ledger-core/virtual/integration/deduplication/find_call_request_handler_test.go
if message came into present pulse we should wait slot to migrate into
past. In this situation old code was setting default migration of whole
SM to "star processing" and never changed default back. This could
result in "re-start" of the operation on two rapid pulse changes.
new code:
* default migration is to "no migration", we should keep running this
handler even if pulse changes
* apply custom `jump(process)` migration only to stepWait using JumpExt,
Repeat of a step doesn't flush migration to default value
there is no sane/stable way to test this with integration test, however
decided to add check that handler SM stops after processing.
> NOISSUE: old code was setting default migration to special and never changed it

- ledger-core/virtual/handlers/handle_meta.go
These messages are needed during execution of VE perf tests which supposed to be executed with info loglevel.
> PLAT-635: change "processing message" loglevel to INFO

- ledger-core/virtual/integration/deduplication/constructor_test.go
each deduplication test has two runs:
* with already sent object data        (~ 1ms)
* with object data that sent on demand (>  1s)
so i've removed all on-demand data sent tests (that doesn't test anything)
> NOISSUE: speedup deduplication tests

- ledger-core/virtual/integration/watermill_integration_test.go
`cnt` was variable shared between two goroutines without lock; replaced with atomic variable
> NOISSUE: fix watermill integration test races

- .github/workflows/long-funcs.yaml
- ledger-core/application/api/availability_test.go
- ledger-core/network/integration/network_test.go
- tags should not contain spaces, because spaces change the condition from AND to OR
- different names for long runs so it would be easier to differ them in slack
> PLAT-583: fixup tags and GA names

- .github/workflows/consensus-checks.yaml
- .github/workflows/linux-checks.yaml
- .github/workflows/master-checks.yaml
- .github/workflows/ve-performance-checks.yaml
use gocenter.io instead of goproxy, because goproxy.io does not respect contract of go mod and can ffail with 410 http error
> NOISSUE: gocenter instead of goproxy

- ledger-core/virtual/execute/execute.go
- ledger-core/virtual/execute/execute.plantuml
- ledger-core/virtual/integration/deduplication_test.go
- ledger-core/virtual/integration/method_pulse_change_test.go
- ledger-core/virtual/integration/method_test.go
VCallRequest must fail with error if interference==intolerable and runner change object state
> PLAT-406: VCallRequest fail with error if interference==intolerable and runner change state

- .github/workflows/linux-checks.yaml
- .github/workflows/windows-checks.yaml
try to fix problem, when GHA running not on the latest commit. It causes here
https://github.com/insolar/assured-ledger/pull/568/checks?check_run_id=901992719
look at commit hashes in "checkout code" job and in left up corner
discussion where i take this solution 
https://github.com/actions/checkout/issues/299
I never done this before, so i hope I do it right
> NOISSUE: fix_ci_runs_on_wrong_commit

- ledger-core/conveyor/sm_pulse_slot.go
- ledger-core/conveyor/sm_pulse_slot.plantuml
Removed priority for present pulse slot as it may prevent worker to get to past pulse slot(s)
> NOISSUE: past eclipsed by present under constant load

- ledger-core/network/hostnetwork/hostnetwork_test.go
Use FakeTransport factory in hostSuite to prevent "connection refused" race.
FakeTransport factory make StreamTransport which don't create real TCP connections
> PLAT-592: bugfix flaky TestHostNetwork_WrongHandler 

- ledger-core/virtual/integration/constructor_test.go
- ledger-core/virtual/integration/method_test.go
- ledger-core/virtual/integration/outgoing_test.go
- ledger-core/virtual/integration/utils/assert_jump.go
- Improve tests to check that requests with logic error not become pending requests
- Test cases from story PLAT-391 updated with AssertNotJumpTo(stepTakeLock)
- TestRail "expected result" updated as well
- test case deleted [C5136](https://insolar.testrail.io/index.php?/cases/view/5136)
* [C4971](https://insolar.testrail.io/index.php?/cases/view/4971)
* [C4974](https://insolar.testrail.io/index.php?/cases/view/4974)
* [C4976](https://insolar.testrail.io/index.php?/cases/view/4976)
* [C4977](https://insolar.testrail.io/index.php?/cases/view/4977)
* [C4979](https://insolar.testrail.io/index.php?/cases/view/4979)
* [C5030](https://insolar.testrail.io/index.php?/cases/view/5030)
> PLAT-524: check that requests with logic error not become pending requests

- ledger-core/network/hostnetwork/hostnetwork_test.go
- ledger-core/network/transport/fake.go
use transport.WaitFakeListeners() to wait until two fake transport starts in Suite and listeners will be ready before test run
> PLAT-592: attempt to fix TestHostNetwork_WrongHandler 

- ledger-core/virtual/integration/deactivate_test.go
deactivation deduplication test scenario
> PLAT-716: deduplicate previous pulse call even object is deactivated in current pulse

- ledger-core/instrumentation/insconveyor/logger_step.go
- ledger-core/virtual/integration/benchs/basic_test.go
* Added a non-reflect marshaller for LogStepInfo
* Allocations are reduced by ~15% in BenchmarkVCallRequestConstructor
> NOISSUE: reduce allocations on conveyor log

- ledger-core/virtual/integration/constructor_test.go
- ledger-core/virtual/integration/outgoing_test.go
add assert in tests VDelegaredRequestFinished if CallType == CallConstructor , then LatestState is not empty
> NOISSUE: add asserts for LatestState

- ledger-core/virtual/integration/statereport_test.go
С4864 is useless, check nothing
C4865, C4919 - remove testwallet and change to table test with all possible statuses
> PLAT-729: remove useless tests and change test with two reports

- ledger-core/virtual/integration/constructor_test.go
subj
```
go test -count=40000 -failfast -run=TestVirtual_CallConstructorFromConstructor ./virtual/integration/...
ok  	github.com/insolar/assured-ledger/ledger-core/virtual/integration	129.247s
ok  	github.com/insolar/assured-ledger/ledger-core/virtual/integration/benchs	0.215s [no tests to run]
ok  	github.com/insolar/assured-ledger/ledger-core/virtual/integration/deduplication	0.269s [no tests to run]
?   	github.com/insolar/assured-ledger/ledger-core/virtual/integration/mock/publisher	[no test files]
?   	github.com/insolar/assured-ledger/ledger-core/virtual/integration/mock/publisher/checker	[no test files]
?   	github.com/insolar/assured-ledger/ledger-core/virtual/integration/mock/publisher/cmd/insolar-mockgenerator-typedpublisher	[no test files]
ok …
```
> PLAT-731: fix TestVirtual_CallConstructorFromConstructor

- ledger-core/virtual/integration/constructor_test.go
> PLAT-665: fix flaky test virtual constructor prev pulse state with missing status

- ledger-core/virtual/integration/deactivate_test.go
SMExecute tries to send message after test stops everything
> PLAT-735: TestVirtual_DeactivateObject panic

- ledger-core/virtual/integration/outgoing_test.go
set new pulse in request for a new token that should come first
do other copy operations before corresponsing checks, not after
IncrementPulse returns
> PLAT-659: IncrementPulse can return when all checks are already failed

- ledger-core/virtual/integration/constructor_test.go
- ledger-core/virtual/integration/deactivate_test.go
- ledger-core/virtual/integration/method_test.go
in all these tests some times SM can finish before we call WaitStopOf
and test finishes with the timeout
> PLAT-767: WaitStopOf should be called before SM is created

- .github/codecov.yml
Because status checks are just enough
> HOTFIX: disable annoying codecov annotations

- ledger-core/conveyor/smachine/api_context.go
- ledger-core/conveyor/smachine/api_shared_link.go
- ledger-core/conveyor/smachine/slot_machine.go
* added ShareDataWithOtherSlotMachines to explicitly enable access to shared data by SM's from other SlotMachines
* GoDoc improvements
> NOISSUE: Access control flag for shared data

- ledger-core/testutils/pulsegenerator.go
- ledger-core/virtual/integration/object_test.go
- ledger-core/virtual/integration/utils/server.go
* pulse time is now 1 second instead of 10 second for VE integration tests (that means delay for waiting of VStateReport 0.1ms instead of 1s)
* fixed one test that relies on 1s delay
> NOISSUE: fix for long running tests

- ledger-core/log/global/struct_log_test.go
Test is time related and is failing with race.
Probably  should be moved to benchmark
> PLAT-830: disable time related checks for now

- ledger-core/virtual/integration/staterequest_test.go
Predicate for Journal wait should be created before payload is sent. If timing is wrong event could happen before wait
> NOISSUE: set journal predicate before payload is sent

- .github/workflows/consensus-checks.yaml
Added manual trigger for consensus checks.
See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/ for details.
> NOISSUE: manual trigger for consensus checks

- ledger-core/virtual/execute/execute.go
> NOISSUE: replace should inherit migration status from origin

- ledger-core/rms/rmsbox/any_lazy.go
- ledger-core/rms/rmsreg/registry.go
* `reflect.New(vType).Interface()` returns pointer to `vType` instance
* `vType` is already a "pointer"
* result object became, for example, `**rms.ROutboundRequest`
* it doesn't implement `rmsreg.unmarshaler` -> `panic`
> NOISSUE: fix pointer conversion in rms

- .github/workflows/consensus-checks.yaml
- .github/workflows/linux-checks.yaml
- .github/workflows/long-integration.yaml
- .github/workflows/master-checks.yaml
- .github/workflows/windows-checks.yaml
Github has deprecated `set-env` and `add-path` echo and introduced `$GITHUB_ENV` and `$GITHUB_PATH` files instead.
> NOISSUE: update `set-env` and `add-path` in GHA workflows

- ledger-core/virtual/lmn/register.go
- ledger-core/virtual/lmn/register.plantuml
DryRun flag gives ability to execute SubSMRegister without sending messages or modifying external state
> NOISSUE: add dry run for SubSMRegister

- ledger-core/rms/rmsbox/binary.go
- ledger-core/rms/rmsbox/record_body.go
- ledger-core/rms/rmsbox/record_payloads.go
- ledger-core/rms/rmsbox/reference.go
- ledger-core/rms/rmsbox/reference_test.go
- ledger-core/vanilla/protokit/binary.go
- ledger-core/vanilla/protokit/binary_test.go
* rmsbox.Reference can distinguish a missing reference and an explicit empty value by a new SetExact() method
> NOISSUE: rmsbox.Reference support for explicit empty value

- .github/workflows/long-integration.yaml
- ledger-core/network/nds/msgdelivery/controller_test.go
* Lowered number of servers in TestMAnyServersEcho from 50 to 15.
* Added manual trigger for long integration tests.
> NOISSUE: Attempt to fix TestManyServersEcho

- ledger-core/testutils/cloud/controller.go
- ledger-core/testutils/cloud/controller_test.go
cloud test should not be run with big count, because ports are not freed immediately
> NOISSUE: exclude cloud test from longtest
